#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="InformationUser")]
	public partial class InformationTableDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFingerPrint(FingerPrint instance);
    partial void UpdateFingerPrint(FingerPrint instance);
    partial void DeleteFingerPrint(FingerPrint instance);
    partial void InsertThongTinCaNhan(ThongTinCaNhan instance);
    partial void UpdateThongTinCaNhan(ThongTinCaNhan instance);
    partial void DeleteThongTinCaNhan(ThongTinCaNhan instance);
    partial void InsertTTCNServer(TTCNServer instance);
    partial void UpdateTTCNServer(TTCNServer instance);
    partial void DeleteTTCNServer(TTCNServer instance);
    #endregion
		
		public InformationTableDBDataContext() : 
				base(global::DBLib.Properties.Settings.Default.InformationUserConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InformationTableDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InformationTableDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InformationTableDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InformationTableDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FingerPrint> FingerPrints
		{
			get
			{
				return this.GetTable<FingerPrint>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinCaNhan> ThongTinCaNhans
		{
			get
			{
				return this.GetTable<ThongTinCaNhan>();
			}
		}
		
		public System.Data.Linq.Table<TTCNServer> TTCNServers
		{
			get
			{
				return this.GetTable<TTCNServer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FingerPrint")]
	public partial class FingerPrint : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _keyId;
		
		private string _strFPNgonCaiPhai;
		
		private string _strFPNgonTroPhai;
		
		private string _strFPNgonCaiTrai;
		
		private string _strFPNgonTroTrai;
		
		private System.Nullable<bool> _status;
		
		private EntitySet<ThongTinCaNhan> _ThongTinCaNhans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkeyIdChanging(int value);
    partial void OnkeyIdChanged();
    partial void OnstrFPNgonCaiPhaiChanging(string value);
    partial void OnstrFPNgonCaiPhaiChanged();
    partial void OnstrFPNgonTroPhaiChanging(string value);
    partial void OnstrFPNgonTroPhaiChanged();
    partial void OnstrFPNgonCaiTraiChanging(string value);
    partial void OnstrFPNgonCaiTraiChanged();
    partial void OnstrFPNgonTroTraiChanging(string value);
    partial void OnstrFPNgonTroTraiChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    #endregion
		
		public FingerPrint()
		{
			this._ThongTinCaNhans = new EntitySet<ThongTinCaNhan>(new Action<ThongTinCaNhan>(this.attach_ThongTinCaNhans), new Action<ThongTinCaNhan>(this.detach_ThongTinCaNhans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int keyId
		{
			get
			{
				return this._keyId;
			}
			set
			{
				if ((this._keyId != value))
				{
					this.OnkeyIdChanging(value);
					this.SendPropertyChanging();
					this._keyId = value;
					this.SendPropertyChanged("keyId");
					this.OnkeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strFPNgonCaiPhai", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strFPNgonCaiPhai
		{
			get
			{
				return this._strFPNgonCaiPhai;
			}
			set
			{
				if ((this._strFPNgonCaiPhai != value))
				{
					this.OnstrFPNgonCaiPhaiChanging(value);
					this.SendPropertyChanging();
					this._strFPNgonCaiPhai = value;
					this.SendPropertyChanged("strFPNgonCaiPhai");
					this.OnstrFPNgonCaiPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strFPNgonTroPhai", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strFPNgonTroPhai
		{
			get
			{
				return this._strFPNgonTroPhai;
			}
			set
			{
				if ((this._strFPNgonTroPhai != value))
				{
					this.OnstrFPNgonTroPhaiChanging(value);
					this.SendPropertyChanging();
					this._strFPNgonTroPhai = value;
					this.SendPropertyChanged("strFPNgonTroPhai");
					this.OnstrFPNgonTroPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strFPNgonCaiTrai", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strFPNgonCaiTrai
		{
			get
			{
				return this._strFPNgonCaiTrai;
			}
			set
			{
				if ((this._strFPNgonCaiTrai != value))
				{
					this.OnstrFPNgonCaiTraiChanging(value);
					this.SendPropertyChanging();
					this._strFPNgonCaiTrai = value;
					this.SendPropertyChanged("strFPNgonCaiTrai");
					this.OnstrFPNgonCaiTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strFPNgonTroTrai", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strFPNgonTroTrai
		{
			get
			{
				return this._strFPNgonTroTrai;
			}
			set
			{
				if ((this._strFPNgonTroTrai != value))
				{
					this.OnstrFPNgonTroTraiChanging(value);
					this.SendPropertyChanging();
					this._strFPNgonTroTrai = value;
					this.SendPropertyChanged("strFPNgonTroTrai");
					this.OnstrFPNgonTroTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FingerPrint_ThongTinCaNhan", Storage="_ThongTinCaNhans", ThisKey="keyId", OtherKey="keyPrintfFinger")]
		public EntitySet<ThongTinCaNhan> ThongTinCaNhans
		{
			get
			{
				return this._ThongTinCaNhans;
			}
			set
			{
				this._ThongTinCaNhans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinCaNhans(ThongTinCaNhan entity)
		{
			this.SendPropertyChanging();
			entity.FingerPrint = this;
		}
		
		private void detach_ThongTinCaNhans(ThongTinCaNhan entity)
		{
			this.SendPropertyChanging();
			entity.FingerPrint = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinCaNhan")]
	public partial class ThongTinCaNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _strHoVaTen;
		
		private string _strCmnd;
		
		private string _strNoiNhanMau;
		
		private string _strKyHieu;
		
		private int _numNamSinh;
		
		private short _strTrinhDo;
		
		private string _strDienThoai1;
		
		private string _strDienThoai2;
		
		private string _strNgheNghiep;
		
		private byte _numTTHonNhan;
		
		private byte _numSoConTrai;
		
		private byte _numSoConGai;
		
		private System.Nullable<bool> _boolConCai;
		
		private System.Nullable<byte> _numBanTinh;
		
		private System.Nullable<bool> _boolCoThai;
		
		private string _strTinhCach;
		
		private string _strNangKhieu;
		
		private string _strUocMuon;
		
		private string _strTaiSaoHienTinh;
		
		private string _strLoiNhanNguoiNhan;
		
		private int _keyPrintfFinger;
		
		private System.Nullable<bool> _status;
		
		private EntityRef<FingerPrint> _FingerPrint;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstrHoVaTenChanging(string value);
    partial void OnstrHoVaTenChanged();
    partial void OnstrCmndChanging(string value);
    partial void OnstrCmndChanged();
    partial void OnstrNoiNhanMauChanging(string value);
    partial void OnstrNoiNhanMauChanged();
    partial void OnstrKyHieuChanging(string value);
    partial void OnstrKyHieuChanged();
    partial void OnnumNamSinhChanging(int value);
    partial void OnnumNamSinhChanged();
    partial void OnstrTrinhDoChanging(short value);
    partial void OnstrTrinhDoChanged();
    partial void OnstrDienThoai1Changing(string value);
    partial void OnstrDienThoai1Changed();
    partial void OnstrDienThoai2Changing(string value);
    partial void OnstrDienThoai2Changed();
    partial void OnstrNgheNghiepChanging(string value);
    partial void OnstrNgheNghiepChanged();
    partial void OnnumTTHonNhanChanging(byte value);
    partial void OnnumTTHonNhanChanged();
    partial void OnnumSoConTraiChanging(byte value);
    partial void OnnumSoConTraiChanged();
    partial void OnnumSoConGaiChanging(byte value);
    partial void OnnumSoConGaiChanged();
    partial void OnboolConCaiChanging(System.Nullable<bool> value);
    partial void OnboolConCaiChanged();
    partial void OnnumBanTinhChanging(System.Nullable<byte> value);
    partial void OnnumBanTinhChanged();
    partial void OnboolCoThaiChanging(System.Nullable<bool> value);
    partial void OnboolCoThaiChanged();
    partial void OnstrTinhCachChanging(string value);
    partial void OnstrTinhCachChanged();
    partial void OnstrNangKhieuChanging(string value);
    partial void OnstrNangKhieuChanged();
    partial void OnstrUocMuonChanging(string value);
    partial void OnstrUocMuonChanged();
    partial void OnstrTaiSaoHienTinhChanging(string value);
    partial void OnstrTaiSaoHienTinhChanged();
    partial void OnstrLoiNhanNguoiNhanChanging(string value);
    partial void OnstrLoiNhanNguoiNhanChanged();
    partial void OnkeyPrintfFingerChanging(int value);
    partial void OnkeyPrintfFingerChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    #endregion
		
		public ThongTinCaNhan()
		{
			this._FingerPrint = default(EntityRef<FingerPrint>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strHoVaTen", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strHoVaTen
		{
			get
			{
				return this._strHoVaTen;
			}
			set
			{
				if ((this._strHoVaTen != value))
				{
					this.OnstrHoVaTenChanging(value);
					this.SendPropertyChanging();
					this._strHoVaTen = value;
					this.SendPropertyChanged("strHoVaTen");
					this.OnstrHoVaTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strCmnd", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strCmnd
		{
			get
			{
				return this._strCmnd;
			}
			set
			{
				if ((this._strCmnd != value))
				{
					this.OnstrCmndChanging(value);
					this.SendPropertyChanging();
					this._strCmnd = value;
					this.SendPropertyChanged("strCmnd");
					this.OnstrCmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNoiNhanMau", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strNoiNhanMau
		{
			get
			{
				return this._strNoiNhanMau;
			}
			set
			{
				if ((this._strNoiNhanMau != value))
				{
					this.OnstrNoiNhanMauChanging(value);
					this.SendPropertyChanging();
					this._strNoiNhanMau = value;
					this.SendPropertyChanged("strNoiNhanMau");
					this.OnstrNoiNhanMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strKyHieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string strKyHieu
		{
			get
			{
				return this._strKyHieu;
			}
			set
			{
				if ((this._strKyHieu != value))
				{
					this.OnstrKyHieuChanging(value);
					this.SendPropertyChanging();
					this._strKyHieu = value;
					this.SendPropertyChanged("strKyHieu");
					this.OnstrKyHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numNamSinh", DbType="Int NOT NULL")]
		public int numNamSinh
		{
			get
			{
				return this._numNamSinh;
			}
			set
			{
				if ((this._numNamSinh != value))
				{
					this.OnnumNamSinhChanging(value);
					this.SendPropertyChanging();
					this._numNamSinh = value;
					this.SendPropertyChanged("numNamSinh");
					this.OnnumNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTrinhDo", DbType="SmallInt NOT NULL")]
		public short strTrinhDo
		{
			get
			{
				return this._strTrinhDo;
			}
			set
			{
				if ((this._strTrinhDo != value))
				{
					this.OnstrTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._strTrinhDo = value;
					this.SendPropertyChanged("strTrinhDo");
					this.OnstrTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strDienThoai1", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strDienThoai1
		{
			get
			{
				return this._strDienThoai1;
			}
			set
			{
				if ((this._strDienThoai1 != value))
				{
					this.OnstrDienThoai1Changing(value);
					this.SendPropertyChanging();
					this._strDienThoai1 = value;
					this.SendPropertyChanged("strDienThoai1");
					this.OnstrDienThoai1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strDienThoai2", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strDienThoai2
		{
			get
			{
				return this._strDienThoai2;
			}
			set
			{
				if ((this._strDienThoai2 != value))
				{
					this.OnstrDienThoai2Changing(value);
					this.SendPropertyChanging();
					this._strDienThoai2 = value;
					this.SendPropertyChanged("strDienThoai2");
					this.OnstrDienThoai2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNgheNghiep", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strNgheNghiep
		{
			get
			{
				return this._strNgheNghiep;
			}
			set
			{
				if ((this._strNgheNghiep != value))
				{
					this.OnstrNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._strNgheNghiep = value;
					this.SendPropertyChanged("strNgheNghiep");
					this.OnstrNgheNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numTTHonNhan", DbType="TinyInt NOT NULL")]
		public byte numTTHonNhan
		{
			get
			{
				return this._numTTHonNhan;
			}
			set
			{
				if ((this._numTTHonNhan != value))
				{
					this.OnnumTTHonNhanChanging(value);
					this.SendPropertyChanging();
					this._numTTHonNhan = value;
					this.SendPropertyChanged("numTTHonNhan");
					this.OnnumTTHonNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numSoConTrai", DbType="TinyInt NOT NULL")]
		public byte numSoConTrai
		{
			get
			{
				return this._numSoConTrai;
			}
			set
			{
				if ((this._numSoConTrai != value))
				{
					this.OnnumSoConTraiChanging(value);
					this.SendPropertyChanging();
					this._numSoConTrai = value;
					this.SendPropertyChanged("numSoConTrai");
					this.OnnumSoConTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numSoConGai", DbType="TinyInt NOT NULL")]
		public byte numSoConGai
		{
			get
			{
				return this._numSoConGai;
			}
			set
			{
				if ((this._numSoConGai != value))
				{
					this.OnnumSoConGaiChanging(value);
					this.SendPropertyChanging();
					this._numSoConGai = value;
					this.SendPropertyChanged("numSoConGai");
					this.OnnumSoConGaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boolConCai", DbType="Bit")]
		public System.Nullable<bool> boolConCai
		{
			get
			{
				return this._boolConCai;
			}
			set
			{
				if ((this._boolConCai != value))
				{
					this.OnboolConCaiChanging(value);
					this.SendPropertyChanging();
					this._boolConCai = value;
					this.SendPropertyChanged("boolConCai");
					this.OnboolConCaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numBanTinh", DbType="TinyInt")]
		public System.Nullable<byte> numBanTinh
		{
			get
			{
				return this._numBanTinh;
			}
			set
			{
				if ((this._numBanTinh != value))
				{
					this.OnnumBanTinhChanging(value);
					this.SendPropertyChanging();
					this._numBanTinh = value;
					this.SendPropertyChanged("numBanTinh");
					this.OnnumBanTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boolCoThai", DbType="Bit")]
		public System.Nullable<bool> boolCoThai
		{
			get
			{
				return this._boolCoThai;
			}
			set
			{
				if ((this._boolCoThai != value))
				{
					this.OnboolCoThaiChanging(value);
					this.SendPropertyChanging();
					this._boolCoThai = value;
					this.SendPropertyChanged("boolCoThai");
					this.OnboolCoThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTinhCach", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strTinhCach
		{
			get
			{
				return this._strTinhCach;
			}
			set
			{
				if ((this._strTinhCach != value))
				{
					this.OnstrTinhCachChanging(value);
					this.SendPropertyChanging();
					this._strTinhCach = value;
					this.SendPropertyChanged("strTinhCach");
					this.OnstrTinhCachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNangKhieu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strNangKhieu
		{
			get
			{
				return this._strNangKhieu;
			}
			set
			{
				if ((this._strNangKhieu != value))
				{
					this.OnstrNangKhieuChanging(value);
					this.SendPropertyChanging();
					this._strNangKhieu = value;
					this.SendPropertyChanged("strNangKhieu");
					this.OnstrNangKhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strUocMuon", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strUocMuon
		{
			get
			{
				return this._strUocMuon;
			}
			set
			{
				if ((this._strUocMuon != value))
				{
					this.OnstrUocMuonChanging(value);
					this.SendPropertyChanging();
					this._strUocMuon = value;
					this.SendPropertyChanged("strUocMuon");
					this.OnstrUocMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTaiSaoHienTinh", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strTaiSaoHienTinh
		{
			get
			{
				return this._strTaiSaoHienTinh;
			}
			set
			{
				if ((this._strTaiSaoHienTinh != value))
				{
					this.OnstrTaiSaoHienTinhChanging(value);
					this.SendPropertyChanging();
					this._strTaiSaoHienTinh = value;
					this.SendPropertyChanged("strTaiSaoHienTinh");
					this.OnstrTaiSaoHienTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strLoiNhanNguoiNhan", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strLoiNhanNguoiNhan
		{
			get
			{
				return this._strLoiNhanNguoiNhan;
			}
			set
			{
				if ((this._strLoiNhanNguoiNhan != value))
				{
					this.OnstrLoiNhanNguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._strLoiNhanNguoiNhan = value;
					this.SendPropertyChanged("strLoiNhanNguoiNhan");
					this.OnstrLoiNhanNguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyPrintfFinger", DbType="Int NOT NULL")]
		public int keyPrintfFinger
		{
			get
			{
				return this._keyPrintfFinger;
			}
			set
			{
				if ((this._keyPrintfFinger != value))
				{
					if (this._FingerPrint.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkeyPrintfFingerChanging(value);
					this.SendPropertyChanging();
					this._keyPrintfFinger = value;
					this.SendPropertyChanged("keyPrintfFinger");
					this.OnkeyPrintfFingerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FingerPrint_ThongTinCaNhan", Storage="_FingerPrint", ThisKey="keyPrintfFinger", OtherKey="keyId", IsForeignKey=true)]
		public FingerPrint FingerPrint
		{
			get
			{
				return this._FingerPrint.Entity;
			}
			set
			{
				FingerPrint previousValue = this._FingerPrint.Entity;
				if (((previousValue != value) 
							|| (this._FingerPrint.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FingerPrint.Entity = null;
						previousValue.ThongTinCaNhans.Remove(this);
					}
					this._FingerPrint.Entity = value;
					if ((value != null))
					{
						value.ThongTinCaNhans.Add(this);
						this._keyPrintfFinger = value.keyId;
					}
					else
					{
						this._keyPrintfFinger = default(int);
					}
					this.SendPropertyChanged("FingerPrint");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTCNServer")]
	public partial class TTCNServer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _strTenTT;
		
		private string _strHoVaTen;
		
		private string _strCmnd;
		
		private System.Nullable<int> _numNamSinh;
		
		private System.Nullable<short> _numTrinhDo;
		
		private string _strNgheNghiep;
		
		private string _strNoiNhanMau;
		
		private System.Nullable<byte> _numTTHonNhan;
		
		private System.Nullable<bool> _boolConCai;
		
		private System.Nullable<byte> _numSoConTrai;
		
		private System.Nullable<byte> _numSoConGai;
		
		private string _strFPNgonCaiPhai;
		
		private string _strFPNgonTroPhai;
		
		private string _strFPNgonCaiTrai;
		
		private string _strFPNgonTroTrai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstrTenTTChanging(string value);
    partial void OnstrTenTTChanged();
    partial void OnstrHoVaTenChanging(string value);
    partial void OnstrHoVaTenChanged();
    partial void OnstrCmndChanging(string value);
    partial void OnstrCmndChanged();
    partial void OnnumNamSinhChanging(System.Nullable<int> value);
    partial void OnnumNamSinhChanged();
    partial void OnnumTrinhDoChanging(System.Nullable<short> value);
    partial void OnnumTrinhDoChanged();
    partial void OnstrNgheNghiepChanging(string value);
    partial void OnstrNgheNghiepChanged();
    partial void OnstrNoiNhanMauChanging(string value);
    partial void OnstrNoiNhanMauChanged();
    partial void OnnumTTHonNhanChanging(System.Nullable<byte> value);
    partial void OnnumTTHonNhanChanged();
    partial void OnboolConCaiChanging(System.Nullable<bool> value);
    partial void OnboolConCaiChanged();
    partial void OnnumSoConTraiChanging(System.Nullable<byte> value);
    partial void OnnumSoConTraiChanged();
    partial void OnnumSoConGaiChanging(System.Nullable<byte> value);
    partial void OnnumSoConGaiChanged();
    partial void OnstrFPNgonCaiPhaiChanging(string value);
    partial void OnstrFPNgonCaiPhaiChanged();
    partial void OnstrFPNgonTroPhaiChanging(string value);
    partial void OnstrFPNgonTroPhaiChanged();
    partial void OnstrFPNgonCaiTraiChanging(string value);
    partial void OnstrFPNgonCaiTraiChanged();
    partial void OnstrFPNgonTroTraiChanging(string value);
    partial void OnstrFPNgonTroTraiChanged();
    #endregion
		
		public TTCNServer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTenTT", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strTenTT
		{
			get
			{
				return this._strTenTT;
			}
			set
			{
				if ((this._strTenTT != value))
				{
					this.OnstrTenTTChanging(value);
					this.SendPropertyChanging();
					this._strTenTT = value;
					this.SendPropertyChanged("strTenTT");
					this.OnstrTenTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strHoVaTen", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strHoVaTen
		{
			get
			{
				return this._strHoVaTen;
			}
			set
			{
				if ((this._strHoVaTen != value))
				{
					this.OnstrHoVaTenChanging(value);
					this.SendPropertyChanging();
					this._strHoVaTen = value;
					this.SendPropertyChanged("strHoVaTen");
					this.OnstrHoVaTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strCmnd", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strCmnd
		{
			get
			{
				return this._strCmnd;
			}
			set
			{
				if ((this._strCmnd != value))
				{
					this.OnstrCmndChanging(value);
					this.SendPropertyChanging();
					this._strCmnd = value;
					this.SendPropertyChanged("strCmnd");
					this.OnstrCmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numNamSinh", DbType="Int")]
		public System.Nullable<int> numNamSinh
		{
			get
			{
				return this._numNamSinh;
			}
			set
			{
				if ((this._numNamSinh != value))
				{
					this.OnnumNamSinhChanging(value);
					this.SendPropertyChanging();
					this._numNamSinh = value;
					this.SendPropertyChanged("numNamSinh");
					this.OnnumNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numTrinhDo", DbType="SmallInt")]
		public System.Nullable<short> numTrinhDo
		{
			get
			{
				return this._numTrinhDo;
			}
			set
			{
				if ((this._numTrinhDo != value))
				{
					this.OnnumTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._numTrinhDo = value;
					this.SendPropertyChanged("numTrinhDo");
					this.OnnumTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNgheNghiep", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strNgheNghiep
		{
			get
			{
				return this._strNgheNghiep;
			}
			set
			{
				if ((this._strNgheNghiep != value))
				{
					this.OnstrNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._strNgheNghiep = value;
					this.SendPropertyChanged("strNgheNghiep");
					this.OnstrNgheNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNoiNhanMau", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strNoiNhanMau
		{
			get
			{
				return this._strNoiNhanMau;
			}
			set
			{
				if ((this._strNoiNhanMau != value))
				{
					this.OnstrNoiNhanMauChanging(value);
					this.SendPropertyChanging();
					this._strNoiNhanMau = value;
					this.SendPropertyChanged("strNoiNhanMau");
					this.OnstrNoiNhanMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numTTHonNhan", DbType="TinyInt")]
		public System.Nullable<byte> numTTHonNhan
		{
			get
			{
				return this._numTTHonNhan;
			}
			set
			{
				if ((this._numTTHonNhan != value))
				{
					this.OnnumTTHonNhanChanging(value);
					this.SendPropertyChanging();
					this._numTTHonNhan = value;
					this.SendPropertyChanged("numTTHonNhan");
					this.OnnumTTHonNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boolConCai", DbType="Bit")]
		public System.Nullable<bool> boolConCai
		{
			get
			{
				return this._boolConCai;
			}
			set
			{
				if ((this._boolConCai != value))
				{
					this.OnboolConCaiChanging(value);
					this.SendPropertyChanging();
					this._boolConCai = value;
					this.SendPropertyChanged("boolConCai");
					this.OnboolConCaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numSoConTrai", DbType="TinyInt")]
		public System.Nullable<byte> numSoConTrai
		{
			get
			{
				return this._numSoConTrai;
			}
			set
			{
				if ((this._numSoConTrai != value))
				{
					this.OnnumSoConTraiChanging(value);
					this.SendPropertyChanging();
					this._numSoConTrai = value;
					this.SendPropertyChanged("numSoConTrai");
					this.OnnumSoConTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numSoConGai", DbType="TinyInt")]
		public System.Nullable<byte> numSoConGai
		{
			get
			{
				return this._numSoConGai;
			}
			set
			{
				if ((this._numSoConGai != value))
				{
					this.OnnumSoConGaiChanging(value);
					this.SendPropertyChanging();
					this._numSoConGai = value;
					this.SendPropertyChanged("numSoConGai");
					this.OnnumSoConGaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strFPNgonCaiPhai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strFPNgonCaiPhai
		{
			get
			{
				return this._strFPNgonCaiPhai;
			}
			set
			{
				if ((this._strFPNgonCaiPhai != value))
				{
					this.OnstrFPNgonCaiPhaiChanging(value);
					this.SendPropertyChanging();
					this._strFPNgonCaiPhai = value;
					this.SendPropertyChanged("strFPNgonCaiPhai");
					this.OnstrFPNgonCaiPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strFPNgonTroPhai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strFPNgonTroPhai
		{
			get
			{
				return this._strFPNgonTroPhai;
			}
			set
			{
				if ((this._strFPNgonTroPhai != value))
				{
					this.OnstrFPNgonTroPhaiChanging(value);
					this.SendPropertyChanging();
					this._strFPNgonTroPhai = value;
					this.SendPropertyChanged("strFPNgonTroPhai");
					this.OnstrFPNgonTroPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strFPNgonCaiTrai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strFPNgonCaiTrai
		{
			get
			{
				return this._strFPNgonCaiTrai;
			}
			set
			{
				if ((this._strFPNgonCaiTrai != value))
				{
					this.OnstrFPNgonCaiTraiChanging(value);
					this.SendPropertyChanging();
					this._strFPNgonCaiTrai = value;
					this.SendPropertyChanged("strFPNgonCaiTrai");
					this.OnstrFPNgonCaiTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strFPNgonTroTrai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string strFPNgonTroTrai
		{
			get
			{
				return this._strFPNgonTroTrai;
			}
			set
			{
				if ((this._strFPNgonTroTrai != value))
				{
					this.OnstrFPNgonTroTraiChanging(value);
					this.SendPropertyChanging();
					this._strFPNgonTroTrai = value;
					this.SendPropertyChanged("strFPNgonTroTrai");
					this.OnstrFPNgonTroTraiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
