#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVPS.DB.DBContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="htss")]
	public partial class QuanLyNguoiNhanMauDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdtb_quanlymau(dtb_quanlymau instance);
    partial void Updatedtb_quanlymau(dtb_quanlymau instance);
    partial void Deletedtb_quanlymau(dtb_quanlymau instance);
    #endregion
		
		public QuanLyNguoiNhanMauDataContext() : 
				base(global::BVPS.DB.Properties.Settings.Default.htssConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNguoiNhanMauDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNguoiNhanMauDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNguoiNhanMauDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNguoiNhanMauDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dtb_quanlymau> dtb_quanlymaus
		{
			get
			{
				return this.GetTable<dtb_quanlymau>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_quanlymau")]
	public partial class dtb_quanlymau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ma_nguoi_hien;
		
		private System.Nullable<System.DateTime> _ngay_luu_tru;
		
		private System.Nullable<System.DateTime> _ngay_su_dung;
		
		private string _ma_nguoi_nhan;
		
		private string _ket_qua_su_dung;
		
		private System.Nullable<bool> _huy_mau;
		
		private System.Nullable<System.DateTime> _ngay_huy_mau;
		
		private string _ghi_chu;
		
		private System.Nullable<bool> _is_approve;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onma_nguoi_hienChanging(string value);
    partial void Onma_nguoi_hienChanged();
    partial void Onngay_luu_truChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_luu_truChanged();
    partial void Onngay_su_dungChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_su_dungChanged();
    partial void Onma_nguoi_nhanChanging(string value);
    partial void Onma_nguoi_nhanChanged();
    partial void Onket_qua_su_dungChanging(string value);
    partial void Onket_qua_su_dungChanged();
    partial void Onhuy_mauChanging(System.Nullable<bool> value);
    partial void Onhuy_mauChanged();
    partial void Onngay_huy_mauChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_huy_mauChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onis_approveChanging(System.Nullable<bool> value);
    partial void Onis_approveChanged();
    #endregion
		
		public dtb_quanlymau()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nguoi_hien", DbType="VarChar(100)")]
		public string ma_nguoi_hien
		{
			get
			{
				return this._ma_nguoi_hien;
			}
			set
			{
				if ((this._ma_nguoi_hien != value))
				{
					this.Onma_nguoi_hienChanging(value);
					this.SendPropertyChanging();
					this._ma_nguoi_hien = value;
					this.SendPropertyChanged("ma_nguoi_hien");
					this.Onma_nguoi_hienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_luu_tru", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_luu_tru
		{
			get
			{
				return this._ngay_luu_tru;
			}
			set
			{
				if ((this._ngay_luu_tru != value))
				{
					this.Onngay_luu_truChanging(value);
					this.SendPropertyChanging();
					this._ngay_luu_tru = value;
					this.SendPropertyChanged("ngay_luu_tru");
					this.Onngay_luu_truChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_su_dung", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_su_dung
		{
			get
			{
				return this._ngay_su_dung;
			}
			set
			{
				if ((this._ngay_su_dung != value))
				{
					this.Onngay_su_dungChanging(value);
					this.SendPropertyChanging();
					this._ngay_su_dung = value;
					this.SendPropertyChanged("ngay_su_dung");
					this.Onngay_su_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nguoi_nhan", DbType="VarChar(100)")]
		public string ma_nguoi_nhan
		{
			get
			{
				return this._ma_nguoi_nhan;
			}
			set
			{
				if ((this._ma_nguoi_nhan != value))
				{
					this.Onma_nguoi_nhanChanging(value);
					this.SendPropertyChanging();
					this._ma_nguoi_nhan = value;
					this.SendPropertyChanged("ma_nguoi_nhan");
					this.Onma_nguoi_nhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ket_qua_su_dung", DbType="NVarChar(50)")]
		public string ket_qua_su_dung
		{
			get
			{
				return this._ket_qua_su_dung;
			}
			set
			{
				if ((this._ket_qua_su_dung != value))
				{
					this.Onket_qua_su_dungChanging(value);
					this.SendPropertyChanging();
					this._ket_qua_su_dung = value;
					this.SendPropertyChanged("ket_qua_su_dung");
					this.Onket_qua_su_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huy_mau", DbType="Bit")]
		public System.Nullable<bool> huy_mau
		{
			get
			{
				return this._huy_mau;
			}
			set
			{
				if ((this._huy_mau != value))
				{
					this.Onhuy_mauChanging(value);
					this.SendPropertyChanging();
					this._huy_mau = value;
					this.SendPropertyChanged("huy_mau");
					this.Onhuy_mauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_huy_mau", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_huy_mau
		{
			get
			{
				return this._ngay_huy_mau;
			}
			set
			{
				if ((this._ngay_huy_mau != value))
				{
					this.Onngay_huy_mauChanging(value);
					this.SendPropertyChanging();
					this._ngay_huy_mau = value;
					this.SendPropertyChanged("ngay_huy_mau");
					this.Onngay_huy_mauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(200)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_approve", DbType="Bit")]
		public System.Nullable<bool> is_approve
		{
			get
			{
				return this._is_approve;
			}
			set
			{
				if ((this._is_approve != value))
				{
					this.Onis_approveChanging(value);
					this.SendPropertyChanging();
					this._is_approve = value;
					this.SendPropertyChanged("is_approve");
					this.Onis_approveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
