#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVPS.DB.DBContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="htss1")]
	public partial class ThongTinBenhNhanHienTinhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdtb_sperm_send(dtb_sperm_send instance);
    partial void Updatedtb_sperm_send(dtb_sperm_send instance);
    partial void Deletedtb_sperm_send(dtb_sperm_send instance);
    partial void Insertdtb_sperm_relation(dtb_sperm_relation instance);
    partial void Updatedtb_sperm_relation(dtb_sperm_relation instance);
    partial void Deletedtb_sperm_relation(dtb_sperm_relation instance);
    partial void Insertdtb_male_facuty(dtb_male_facuty instance);
    partial void Updatedtb_male_facuty(dtb_male_facuty instance);
    partial void Deletedtb_male_facuty(dtb_male_facuty instance);
    partial void Insertdtb_lab_result(dtb_lab_result instance);
    partial void Updatedtb_lab_result(dtb_lab_result instance);
    partial void Deletedtb_lab_result(dtb_lab_result instance);
    partial void Insertdtb_pattern_storage(dtb_pattern_storage instance);
    partial void Updatedtb_pattern_storage(dtb_pattern_storage instance);
    partial void Deletedtb_pattern_storage(dtb_pattern_storage instance);
    partial void Insertdtb_ttd_result(dtb_ttd_result instance);
    partial void Updatedtb_ttd_result(dtb_ttd_result instance);
    partial void Deletedtb_ttd_result(dtb_ttd_result instance);
    partial void Insertdtb_male_relation(dtb_male_relation instance);
    partial void Updatedtb_male_relation(dtb_male_relation instance);
    partial void Deletedtb_male_relation(dtb_male_relation instance);
    partial void Insertdtb_sperm_spec(dtb_sperm_spec instance);
    partial void Updatedtb_sperm_spec(dtb_sperm_spec instance);
    partial void Deletedtb_sperm_spec(dtb_sperm_spec instance);
    #endregion
		
		public ThongTinBenhNhanHienTinhDataContext() : 
				base(global::BVPS.DB.Properties.Settings.Default.htss1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThongTinBenhNhanHienTinhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongTinBenhNhanHienTinhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongTinBenhNhanHienTinhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongTinBenhNhanHienTinhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dtb_sperm_send> dtb_sperm_sends
		{
			get
			{
				return this.GetTable<dtb_sperm_send>();
			}
		}
		
		public System.Data.Linq.Table<dtb_sperm_relation> dtb_sperm_relations
		{
			get
			{
				return this.GetTable<dtb_sperm_relation>();
			}
		}
		
		public System.Data.Linq.Table<dtb_male_facuty> dtb_male_facuties
		{
			get
			{
				return this.GetTable<dtb_male_facuty>();
			}
		}
		
		public System.Data.Linq.Table<dtb_lab_result> dtb_lab_results
		{
			get
			{
				return this.GetTable<dtb_lab_result>();
			}
		}
		
		public System.Data.Linq.Table<dtb_pattern_storage> dtb_pattern_storages
		{
			get
			{
				return this.GetTable<dtb_pattern_storage>();
			}
		}
		
		public System.Data.Linq.Table<dtb_ttd_result> dtb_ttd_results
		{
			get
			{
				return this.GetTable<dtb_ttd_result>();
			}
		}
		
		public System.Data.Linq.Table<dtb_male_relation> dtb_male_relations
		{
			get
			{
				return this.GetTable<dtb_male_relation>();
			}
		}
		
		public System.Data.Linq.Table<dtb_sperm_spec> dtb_sperm_specs
		{
			get
			{
				return this.GetTable<dtb_sperm_spec>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_sperm_send")]
	public partial class dtb_sperm_send : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _patient_code;
		
		private string _fullname;
		
		private System.Nullable<System.DateTime> _date_of_birth;
		
		private string _identifier;
		
		private System.Nullable<System.DateTime> _date_of_id;
		
		private string _address_of_id;
		
		private string _address;
		
		private string _phone;
		
		private string _email;
		
		private System.Nullable<int> _level_id;
		
		private string _job;
		
		private System.Nullable<int> _nation_id;
		
		private System.Nullable<int> _class_id;
		
		private string _province_code;
		
		private string _district_code;
		
		private System.Nullable<bool> _maried;
		
		private System.Nullable<bool> _has_child;
		
		private System.Nullable<int> _num_of_child;
		
		private System.Nullable<int> _year_of_child_last;
		
		private System.Nullable<int> _day_of_have_baby;
		
		private string _heath_status;
		
		private string _history_of_patient;
		
		private string _fp_ngon_cai_phai;
		
		private string _fp_ngon_cai_trai;
		
		private string _fp_ngon_tro_phai;
		
		private string _fp_ngon_tro_trai;
		
		private string _history_of_family;
		
		private string _fp_base64_ngon_cai_phai;
		
		private string _fp_base64_ngon_cai_trai;
		
		private string _fp_base64_ngon_tro_phai;
		
		private string _fp_base64_ngon_tro_trai;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private System.Nullable<bool> _flag_allow_add_pattern;
		
		private System.Nullable<bool> _flag_need_sync;
		
		private string _ma_tt;
		
		private System.Nullable<bool> _flag_approve;
		
		private System.Nullable<byte> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    partial void OnidentifierChanging(string value);
    partial void OnidentifierChanged();
    partial void Ondate_of_idChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_idChanged();
    partial void Onaddress_of_idChanging(string value);
    partial void Onaddress_of_idChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onlevel_idChanging(System.Nullable<int> value);
    partial void Onlevel_idChanged();
    partial void OnjobChanging(string value);
    partial void OnjobChanged();
    partial void Onnation_idChanging(System.Nullable<int> value);
    partial void Onnation_idChanged();
    partial void Onclass_idChanging(System.Nullable<int> value);
    partial void Onclass_idChanged();
    partial void Onprovince_codeChanging(string value);
    partial void Onprovince_codeChanged();
    partial void Ondistrict_codeChanging(string value);
    partial void Ondistrict_codeChanged();
    partial void OnmariedChanging(System.Nullable<bool> value);
    partial void OnmariedChanged();
    partial void Onhas_childChanging(System.Nullable<bool> value);
    partial void Onhas_childChanged();
    partial void Onnum_of_childChanging(System.Nullable<int> value);
    partial void Onnum_of_childChanged();
    partial void Onyear_of_child_lastChanging(System.Nullable<int> value);
    partial void Onyear_of_child_lastChanged();
    partial void Onday_of_have_babyChanging(System.Nullable<int> value);
    partial void Onday_of_have_babyChanged();
    partial void Onheath_statusChanging(string value);
    partial void Onheath_statusChanged();
    partial void Onhistory_of_patientChanging(string value);
    partial void Onhistory_of_patientChanged();
    partial void Onfp_ngon_cai_phaiChanging(string value);
    partial void Onfp_ngon_cai_phaiChanged();
    partial void Onfp_ngon_cai_traiChanging(string value);
    partial void Onfp_ngon_cai_traiChanged();
    partial void Onfp_ngon_tro_phaiChanging(string value);
    partial void Onfp_ngon_tro_phaiChanged();
    partial void Onfp_ngon_tro_traiChanging(string value);
    partial void Onfp_ngon_tro_traiChanged();
    partial void Onhistory_of_familyChanging(string value);
    partial void Onhistory_of_familyChanged();
    partial void Onfp_base64_ngon_cai_phaiChanging(string value);
    partial void Onfp_base64_ngon_cai_phaiChanged();
    partial void Onfp_base64_ngon_cai_traiChanging(string value);
    partial void Onfp_base64_ngon_cai_traiChanged();
    partial void Onfp_base64_ngon_tro_phaiChanging(string value);
    partial void Onfp_base64_ngon_tro_phaiChanged();
    partial void Onfp_base64_ngon_tro_traiChanging(string value);
    partial void Onfp_base64_ngon_tro_traiChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onflag_allow_add_patternChanging(System.Nullable<bool> value);
    partial void Onflag_allow_add_patternChanged();
    partial void Onflag_need_syncChanging(System.Nullable<bool> value);
    partial void Onflag_need_syncChanged();
    partial void Onma_ttChanging(string value);
    partial void Onma_ttChanged();
    partial void Onflag_approveChanging(System.Nullable<bool> value);
    partial void Onflag_approveChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    #endregion
		
		public dtb_sperm_send()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(100)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_birth
		{
			get
			{
				return this._date_of_birth;
			}
			set
			{
				if ((this._date_of_birth != value))
				{
					this.Ondate_of_birthChanging(value);
					this.SendPropertyChanging();
					this._date_of_birth = value;
					this.SendPropertyChanged("date_of_birth");
					this.Ondate_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="VarChar(100)")]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this.OnidentifierChanging(value);
					this.SendPropertyChanging();
					this._identifier = value;
					this.SendPropertyChanged("identifier");
					this.OnidentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_id", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_id
		{
			get
			{
				return this._date_of_id;
			}
			set
			{
				if ((this._date_of_id != value))
				{
					this.Ondate_of_idChanging(value);
					this.SendPropertyChanging();
					this._date_of_id = value;
					this.SendPropertyChanged("date_of_id");
					this.Ondate_of_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_of_id", DbType="NVarChar(100)")]
		public string address_of_id
		{
			get
			{
				return this._address_of_id;
			}
			set
			{
				if ((this._address_of_id != value))
				{
					this.Onaddress_of_idChanging(value);
					this.SendPropertyChanging();
					this._address_of_id = value;
					this.SendPropertyChanged("address_of_id");
					this.Onaddress_of_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_id", DbType="Int")]
		public System.Nullable<int> level_id
		{
			get
			{
				return this._level_id;
			}
			set
			{
				if ((this._level_id != value))
				{
					this.Onlevel_idChanging(value);
					this.SendPropertyChanging();
					this._level_id = value;
					this.SendPropertyChanged("level_id");
					this.Onlevel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job", DbType="NVarChar(100)")]
		public string job
		{
			get
			{
				return this._job;
			}
			set
			{
				if ((this._job != value))
				{
					this.OnjobChanging(value);
					this.SendPropertyChanging();
					this._job = value;
					this.SendPropertyChanged("job");
					this.OnjobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nation_id", DbType="Int")]
		public System.Nullable<int> nation_id
		{
			get
			{
				return this._nation_id;
			}
			set
			{
				if ((this._nation_id != value))
				{
					this.Onnation_idChanging(value);
					this.SendPropertyChanging();
					this._nation_id = value;
					this.SendPropertyChanged("nation_id");
					this.Onnation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_id", DbType="Int")]
		public System.Nullable<int> class_id
		{
			get
			{
				return this._class_id;
			}
			set
			{
				if ((this._class_id != value))
				{
					this.Onclass_idChanging(value);
					this.SendPropertyChanging();
					this._class_id = value;
					this.SendPropertyChanged("class_id");
					this.Onclass_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province_code", DbType="VarChar(100)")]
		public string province_code
		{
			get
			{
				return this._province_code;
			}
			set
			{
				if ((this._province_code != value))
				{
					this.Onprovince_codeChanging(value);
					this.SendPropertyChanging();
					this._province_code = value;
					this.SendPropertyChanged("province_code");
					this.Onprovince_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district_code", DbType="VarChar(100)")]
		public string district_code
		{
			get
			{
				return this._district_code;
			}
			set
			{
				if ((this._district_code != value))
				{
					this.Ondistrict_codeChanging(value);
					this.SendPropertyChanging();
					this._district_code = value;
					this.SendPropertyChanged("district_code");
					this.Ondistrict_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maried", DbType="Bit")]
		public System.Nullable<bool> maried
		{
			get
			{
				return this._maried;
			}
			set
			{
				if ((this._maried != value))
				{
					this.OnmariedChanging(value);
					this.SendPropertyChanging();
					this._maried = value;
					this.SendPropertyChanged("maried");
					this.OnmariedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_child", DbType="Bit")]
		public System.Nullable<bool> has_child
		{
			get
			{
				return this._has_child;
			}
			set
			{
				if ((this._has_child != value))
				{
					this.Onhas_childChanging(value);
					this.SendPropertyChanging();
					this._has_child = value;
					this.SendPropertyChanged("has_child");
					this.Onhas_childChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_of_child", DbType="Int")]
		public System.Nullable<int> num_of_child
		{
			get
			{
				return this._num_of_child;
			}
			set
			{
				if ((this._num_of_child != value))
				{
					this.Onnum_of_childChanging(value);
					this.SendPropertyChanging();
					this._num_of_child = value;
					this.SendPropertyChanged("num_of_child");
					this.Onnum_of_childChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_of_child_last", DbType="Int")]
		public System.Nullable<int> year_of_child_last
		{
			get
			{
				return this._year_of_child_last;
			}
			set
			{
				if ((this._year_of_child_last != value))
				{
					this.Onyear_of_child_lastChanging(value);
					this.SendPropertyChanging();
					this._year_of_child_last = value;
					this.SendPropertyChanged("year_of_child_last");
					this.Onyear_of_child_lastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day_of_have_baby", DbType="Int")]
		public System.Nullable<int> day_of_have_baby
		{
			get
			{
				return this._day_of_have_baby;
			}
			set
			{
				if ((this._day_of_have_baby != value))
				{
					this.Onday_of_have_babyChanging(value);
					this.SendPropertyChanging();
					this._day_of_have_baby = value;
					this.SendPropertyChanged("day_of_have_baby");
					this.Onday_of_have_babyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heath_status", DbType="NVarChar(100)")]
		public string heath_status
		{
			get
			{
				return this._heath_status;
			}
			set
			{
				if ((this._heath_status != value))
				{
					this.Onheath_statusChanging(value);
					this.SendPropertyChanging();
					this._heath_status = value;
					this.SendPropertyChanged("heath_status");
					this.Onheath_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_history_of_patient", DbType="NVarChar(100)")]
		public string history_of_patient
		{
			get
			{
				return this._history_of_patient;
			}
			set
			{
				if ((this._history_of_patient != value))
				{
					this.Onhistory_of_patientChanging(value);
					this.SendPropertyChanging();
					this._history_of_patient = value;
					this.SendPropertyChanged("history_of_patient");
					this.Onhistory_of_patientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fp_ngon_cai_phai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string fp_ngon_cai_phai
		{
			get
			{
				return this._fp_ngon_cai_phai;
			}
			set
			{
				if ((this._fp_ngon_cai_phai != value))
				{
					this.Onfp_ngon_cai_phaiChanging(value);
					this.SendPropertyChanging();
					this._fp_ngon_cai_phai = value;
					this.SendPropertyChanged("fp_ngon_cai_phai");
					this.Onfp_ngon_cai_phaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fp_ngon_cai_trai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string fp_ngon_cai_trai
		{
			get
			{
				return this._fp_ngon_cai_trai;
			}
			set
			{
				if ((this._fp_ngon_cai_trai != value))
				{
					this.Onfp_ngon_cai_traiChanging(value);
					this.SendPropertyChanging();
					this._fp_ngon_cai_trai = value;
					this.SendPropertyChanged("fp_ngon_cai_trai");
					this.Onfp_ngon_cai_traiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fp_ngon_tro_phai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string fp_ngon_tro_phai
		{
			get
			{
				return this._fp_ngon_tro_phai;
			}
			set
			{
				if ((this._fp_ngon_tro_phai != value))
				{
					this.Onfp_ngon_tro_phaiChanging(value);
					this.SendPropertyChanging();
					this._fp_ngon_tro_phai = value;
					this.SendPropertyChanged("fp_ngon_tro_phai");
					this.Onfp_ngon_tro_phaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fp_ngon_tro_trai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string fp_ngon_tro_trai
		{
			get
			{
				return this._fp_ngon_tro_trai;
			}
			set
			{
				if ((this._fp_ngon_tro_trai != value))
				{
					this.Onfp_ngon_tro_traiChanging(value);
					this.SendPropertyChanging();
					this._fp_ngon_tro_trai = value;
					this.SendPropertyChanged("fp_ngon_tro_trai");
					this.Onfp_ngon_tro_traiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_history_of_family", DbType="NVarChar(100)")]
		public string history_of_family
		{
			get
			{
				return this._history_of_family;
			}
			set
			{
				if ((this._history_of_family != value))
				{
					this.Onhistory_of_familyChanging(value);
					this.SendPropertyChanging();
					this._history_of_family = value;
					this.SendPropertyChanged("history_of_family");
					this.Onhistory_of_familyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fp_base64_ngon_cai_phai", DbType="NVarChar(MAX)")]
		public string fp_base64_ngon_cai_phai
		{
			get
			{
				return this._fp_base64_ngon_cai_phai;
			}
			set
			{
				if ((this._fp_base64_ngon_cai_phai != value))
				{
					this.Onfp_base64_ngon_cai_phaiChanging(value);
					this.SendPropertyChanging();
					this._fp_base64_ngon_cai_phai = value;
					this.SendPropertyChanged("fp_base64_ngon_cai_phai");
					this.Onfp_base64_ngon_cai_phaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fp_base64_ngon_cai_trai", DbType="NVarChar(MAX)")]
		public string fp_base64_ngon_cai_trai
		{
			get
			{
				return this._fp_base64_ngon_cai_trai;
			}
			set
			{
				if ((this._fp_base64_ngon_cai_trai != value))
				{
					this.Onfp_base64_ngon_cai_traiChanging(value);
					this.SendPropertyChanging();
					this._fp_base64_ngon_cai_trai = value;
					this.SendPropertyChanged("fp_base64_ngon_cai_trai");
					this.Onfp_base64_ngon_cai_traiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fp_base64_ngon_tro_phai", DbType="NVarChar(MAX)")]
		public string fp_base64_ngon_tro_phai
		{
			get
			{
				return this._fp_base64_ngon_tro_phai;
			}
			set
			{
				if ((this._fp_base64_ngon_tro_phai != value))
				{
					this.Onfp_base64_ngon_tro_phaiChanging(value);
					this.SendPropertyChanging();
					this._fp_base64_ngon_tro_phai = value;
					this.SendPropertyChanged("fp_base64_ngon_tro_phai");
					this.Onfp_base64_ngon_tro_phaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fp_base64_ngon_tro_trai", DbType="NVarChar(MAX)")]
		public string fp_base64_ngon_tro_trai
		{
			get
			{
				return this._fp_base64_ngon_tro_trai;
			}
			set
			{
				if ((this._fp_base64_ngon_tro_trai != value))
				{
					this.Onfp_base64_ngon_tro_traiChanging(value);
					this.SendPropertyChanging();
					this._fp_base64_ngon_tro_trai = value;
					this.SendPropertyChanged("fp_base64_ngon_tro_trai");
					this.Onfp_base64_ngon_tro_traiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_allow_add_pattern", DbType="Bit")]
		public System.Nullable<bool> flag_allow_add_pattern
		{
			get
			{
				return this._flag_allow_add_pattern;
			}
			set
			{
				if ((this._flag_allow_add_pattern != value))
				{
					this.Onflag_allow_add_patternChanging(value);
					this.SendPropertyChanging();
					this._flag_allow_add_pattern = value;
					this.SendPropertyChanged("flag_allow_add_pattern");
					this.Onflag_allow_add_patternChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_need_sync", DbType="Bit")]
		public System.Nullable<bool> flag_need_sync
		{
			get
			{
				return this._flag_need_sync;
			}
			set
			{
				if ((this._flag_need_sync != value))
				{
					this.Onflag_need_syncChanging(value);
					this.SendPropertyChanging();
					this._flag_need_sync = value;
					this.SendPropertyChanged("flag_need_sync");
					this.Onflag_need_syncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tt", DbType="NVarChar(10)")]
		public string ma_tt
		{
			get
			{
				return this._ma_tt;
			}
			set
			{
				if ((this._ma_tt != value))
				{
					this.Onma_ttChanging(value);
					this.SendPropertyChanging();
					this._ma_tt = value;
					this.SendPropertyChanged("ma_tt");
					this.Onma_ttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_approve", DbType="Bit")]
		public System.Nullable<bool> flag_approve
		{
			get
			{
				return this._flag_approve;
			}
			set
			{
				if ((this._flag_approve != value))
				{
					this.Onflag_approveChanging(value);
					this.SendPropertyChanging();
					this._flag_approve = value;
					this.SendPropertyChanged("flag_approve");
					this.Onflag_approveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_sperm_relation")]
	public partial class dtb_sperm_relation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _patient_code;
		
		private string _fullname;
		
		private string _identify;
		
		private System.Nullable<System.DateTime> _date_of_birth;
		
		private System.Nullable<System.DateTime> _date_of_id;
		
		private string _address;
		
		private string _address_of_id;
		
		private string _phone;
		
		private string _email;
		
		private string _ghi_chu;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private System.Nullable<bool> _flag_need_sync;
		
		private System.Nullable<byte> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnidentifyChanging(string value);
    partial void OnidentifyChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    partial void Ondate_of_idChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_idChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Onaddress_of_idChanging(string value);
    partial void Onaddress_of_idChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onflag_need_syncChanging(System.Nullable<bool> value);
    partial void Onflag_need_syncChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    #endregion
		
		public dtb_sperm_relation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(100)")]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(100)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identify", DbType="VarChar(100)")]
		public string identify
		{
			get
			{
				return this._identify;
			}
			set
			{
				if ((this._identify != value))
				{
					this.OnidentifyChanging(value);
					this.SendPropertyChanging();
					this._identify = value;
					this.SendPropertyChanged("identify");
					this.OnidentifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_birth
		{
			get
			{
				return this._date_of_birth;
			}
			set
			{
				if ((this._date_of_birth != value))
				{
					this.Ondate_of_birthChanging(value);
					this.SendPropertyChanging();
					this._date_of_birth = value;
					this.SendPropertyChanged("date_of_birth");
					this.Ondate_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_id", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_id
		{
			get
			{
				return this._date_of_id;
			}
			set
			{
				if ((this._date_of_id != value))
				{
					this.Ondate_of_idChanging(value);
					this.SendPropertyChanging();
					this._date_of_id = value;
					this.SendPropertyChanged("date_of_id");
					this.Ondate_of_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_of_id", DbType="NVarChar(100)")]
		public string address_of_id
		{
			get
			{
				return this._address_of_id;
			}
			set
			{
				if ((this._address_of_id != value))
				{
					this.Onaddress_of_idChanging(value);
					this.SendPropertyChanging();
					this._address_of_id = value;
					this.SendPropertyChanged("address_of_id");
					this.Onaddress_of_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(500)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_need_sync", DbType="Bit")]
		public System.Nullable<bool> flag_need_sync
		{
			get
			{
				return this._flag_need_sync;
			}
			set
			{
				if ((this._flag_need_sync != value))
				{
					this.Onflag_need_syncChanging(value);
					this.SendPropertyChanging();
					this._flag_need_sync = value;
					this.SendPropertyChanged("flag_need_sync");
					this.Onflag_need_syncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_male_facuty")]
	public partial class dtb_male_facuty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _tt_left;
		
		private string _tt_right;
		
		private string _mao_tinh;
		
		private string _ong_dan_tinh;
		
		private string _varicole;
		
		private string _duong_vat;
		
		private string _dac_tinh_sinh_san;
		
		private string _patient_code;
		
		private string _ghi_chu;
		
		private System.Nullable<bool> _flag_need_sync;
		
		private System.Nullable<byte> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Ontt_leftChanging(string value);
    partial void Ontt_leftChanged();
    partial void Ontt_rightChanging(string value);
    partial void Ontt_rightChanged();
    partial void Onmao_tinhChanging(string value);
    partial void Onmao_tinhChanged();
    partial void Onong_dan_tinhChanging(string value);
    partial void Onong_dan_tinhChanged();
    partial void OnvaricoleChanging(string value);
    partial void OnvaricoleChanged();
    partial void Onduong_vatChanging(string value);
    partial void Onduong_vatChanged();
    partial void Ondac_tinh_sinh_sanChanging(string value);
    partial void Ondac_tinh_sinh_sanChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onflag_need_syncChanging(System.Nullable<bool> value);
    partial void Onflag_need_syncChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    #endregion
		
		public dtb_male_facuty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_left", DbType="NVarChar(100)")]
		public string tt_left
		{
			get
			{
				return this._tt_left;
			}
			set
			{
				if ((this._tt_left != value))
				{
					this.Ontt_leftChanging(value);
					this.SendPropertyChanging();
					this._tt_left = value;
					this.SendPropertyChanged("tt_left");
					this.Ontt_leftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_right", DbType="NVarChar(100)")]
		public string tt_right
		{
			get
			{
				return this._tt_right;
			}
			set
			{
				if ((this._tt_right != value))
				{
					this.Ontt_rightChanging(value);
					this.SendPropertyChanging();
					this._tt_right = value;
					this.SendPropertyChanged("tt_right");
					this.Ontt_rightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mao_tinh", DbType="NVarChar(100)")]
		public string mao_tinh
		{
			get
			{
				return this._mao_tinh;
			}
			set
			{
				if ((this._mao_tinh != value))
				{
					this.Onmao_tinhChanging(value);
					this.SendPropertyChanging();
					this._mao_tinh = value;
					this.SendPropertyChanged("mao_tinh");
					this.Onmao_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ong_dan_tinh", DbType="NVarChar(100)")]
		public string ong_dan_tinh
		{
			get
			{
				return this._ong_dan_tinh;
			}
			set
			{
				if ((this._ong_dan_tinh != value))
				{
					this.Onong_dan_tinhChanging(value);
					this.SendPropertyChanging();
					this._ong_dan_tinh = value;
					this.SendPropertyChanged("ong_dan_tinh");
					this.Onong_dan_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_varicole", DbType="NVarChar(100)")]
		public string varicole
		{
			get
			{
				return this._varicole;
			}
			set
			{
				if ((this._varicole != value))
				{
					this.OnvaricoleChanging(value);
					this.SendPropertyChanging();
					this._varicole = value;
					this.SendPropertyChanged("varicole");
					this.OnvaricoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duong_vat", DbType="NVarChar(100)")]
		public string duong_vat
		{
			get
			{
				return this._duong_vat;
			}
			set
			{
				if ((this._duong_vat != value))
				{
					this.Onduong_vatChanging(value);
					this.SendPropertyChanging();
					this._duong_vat = value;
					this.SendPropertyChanged("duong_vat");
					this.Onduong_vatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dac_tinh_sinh_san", DbType="NVarChar(100)")]
		public string dac_tinh_sinh_san
		{
			get
			{
				return this._dac_tinh_sinh_san;
			}
			set
			{
				if ((this._dac_tinh_sinh_san != value))
				{
					this.Ondac_tinh_sinh_sanChanging(value);
					this.SendPropertyChanging();
					this._dac_tinh_sinh_san = value;
					this.SendPropertyChanged("dac_tinh_sinh_san");
					this.Ondac_tinh_sinh_sanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(100)")]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(500)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_need_sync", DbType="Bit")]
		public System.Nullable<bool> flag_need_sync
		{
			get
			{
				return this._flag_need_sync;
			}
			set
			{
				if ((this._flag_need_sync != value))
				{
					this.Onflag_need_syncChanging(value);
					this.SendPropertyChanging();
					this._flag_need_sync = value;
					this.SendPropertyChanged("flag_need_sync");
					this.Onflag_need_syncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_lab_result")]
	public partial class dtb_lab_result : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _group_blood;
		
		private string _hiv;
		
		private string _bw;
		
		private string _hbsag;
		
		private string _antihcv;
		
		private string _patient_code;
		
		private System.Nullable<int> _num_of_check;
		
		private string _ghi_chu;
		
		private System.Nullable<bool> _flag_need_sync;
		
		private System.Nullable<byte> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Ongroup_bloodChanging(string value);
    partial void Ongroup_bloodChanged();
    partial void OnhivChanging(string value);
    partial void OnhivChanged();
    partial void OnbwChanging(string value);
    partial void OnbwChanged();
    partial void OnhbsagChanging(string value);
    partial void OnhbsagChanged();
    partial void OnantihcvChanging(string value);
    partial void OnantihcvChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void Onnum_of_checkChanging(System.Nullable<int> value);
    partial void Onnum_of_checkChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onflag_need_syncChanging(System.Nullable<bool> value);
    partial void Onflag_need_syncChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    #endregion
		
		public dtb_lab_result()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_blood", DbType="NVarChar(50)")]
		public string group_blood
		{
			get
			{
				return this._group_blood;
			}
			set
			{
				if ((this._group_blood != value))
				{
					this.Ongroup_bloodChanging(value);
					this.SendPropertyChanging();
					this._group_blood = value;
					this.SendPropertyChanged("group_blood");
					this.Ongroup_bloodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiv", DbType="NVarChar(50)")]
		public string hiv
		{
			get
			{
				return this._hiv;
			}
			set
			{
				if ((this._hiv != value))
				{
					this.OnhivChanging(value);
					this.SendPropertyChanging();
					this._hiv = value;
					this.SendPropertyChanged("hiv");
					this.OnhivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bw", DbType="NVarChar(50)")]
		public string bw
		{
			get
			{
				return this._bw;
			}
			set
			{
				if ((this._bw != value))
				{
					this.OnbwChanging(value);
					this.SendPropertyChanging();
					this._bw = value;
					this.SendPropertyChanged("bw");
					this.OnbwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hbsag", DbType="NVarChar(50)")]
		public string hbsag
		{
			get
			{
				return this._hbsag;
			}
			set
			{
				if ((this._hbsag != value))
				{
					this.OnhbsagChanging(value);
					this.SendPropertyChanging();
					this._hbsag = value;
					this.SendPropertyChanged("hbsag");
					this.OnhbsagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_antihcv", DbType="NVarChar(50)")]
		public string antihcv
		{
			get
			{
				return this._antihcv;
			}
			set
			{
				if ((this._antihcv != value))
				{
					this.OnantihcvChanging(value);
					this.SendPropertyChanging();
					this._antihcv = value;
					this.SendPropertyChanged("antihcv");
					this.OnantihcvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(50)")]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_of_check", DbType="Int")]
		public System.Nullable<int> num_of_check
		{
			get
			{
				return this._num_of_check;
			}
			set
			{
				if ((this._num_of_check != value))
				{
					this.Onnum_of_checkChanging(value);
					this.SendPropertyChanging();
					this._num_of_check = value;
					this.SendPropertyChanged("num_of_check");
					this.Onnum_of_checkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(500)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_need_sync", DbType="Bit")]
		public System.Nullable<bool> flag_need_sync
		{
			get
			{
				return this._flag_need_sync;
			}
			set
			{
				if ((this._flag_need_sync != value))
				{
					this.Onflag_need_syncChanging(value);
					this.SendPropertyChanging();
					this._flag_need_sync = value;
					this.SendPropertyChanged("flag_need_sync");
					this.Onflag_need_syncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_pattern_storage")]
	public partial class dtb_pattern_storage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _patient_code;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _mat_do;
		
		private string _di_dong;
		
		private string _hinh_dang;
		
		private string _vi_tri;
		
		private System.Nullable<bool> _has_condition;
		
		private string _reason;
		
		private System.Nullable<bool> _has_gennetic;
		
		private string _ghi_chu;
		
		private System.Nullable<bool> _flag_need_sync;
		
		private System.Nullable<byte> _status;
		
		private System.Nullable<bool> _flag_used;
		
		private string _pattern_code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onmat_doChanging(string value);
    partial void Onmat_doChanged();
    partial void Ondi_dongChanging(string value);
    partial void Ondi_dongChanged();
    partial void Onhinh_dangChanging(string value);
    partial void Onhinh_dangChanged();
    partial void Onvi_triChanging(string value);
    partial void Onvi_triChanged();
    partial void Onhas_conditionChanging(System.Nullable<bool> value);
    partial void Onhas_conditionChanged();
    partial void OnreasonChanging(string value);
    partial void OnreasonChanged();
    partial void Onhas_genneticChanging(System.Nullable<bool> value);
    partial void Onhas_genneticChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onflag_need_syncChanging(System.Nullable<bool> value);
    partial void Onflag_need_syncChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    partial void Onflag_usedChanging(System.Nullable<bool> value);
    partial void Onflag_usedChanged();
    partial void Onpattern_codeChanging(string value);
    partial void Onpattern_codeChanged();
    #endregion
		
		public dtb_pattern_storage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(100)")]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_do", DbType="NVarChar(100)")]
		public string mat_do
		{
			get
			{
				return this._mat_do;
			}
			set
			{
				if ((this._mat_do != value))
				{
					this.Onmat_doChanging(value);
					this.SendPropertyChanging();
					this._mat_do = value;
					this.SendPropertyChanged("mat_do");
					this.Onmat_doChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_di_dong", DbType="NVarChar(100)")]
		public string di_dong
		{
			get
			{
				return this._di_dong;
			}
			set
			{
				if ((this._di_dong != value))
				{
					this.Ondi_dongChanging(value);
					this.SendPropertyChanging();
					this._di_dong = value;
					this.SendPropertyChanged("di_dong");
					this.Ondi_dongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_dang", DbType="NVarChar(100)")]
		public string hinh_dang
		{
			get
			{
				return this._hinh_dang;
			}
			set
			{
				if ((this._hinh_dang != value))
				{
					this.Onhinh_dangChanging(value);
					this.SendPropertyChanging();
					this._hinh_dang = value;
					this.SendPropertyChanged("hinh_dang");
					this.Onhinh_dangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vi_tri", DbType="NVarChar(100)")]
		public string vi_tri
		{
			get
			{
				return this._vi_tri;
			}
			set
			{
				if ((this._vi_tri != value))
				{
					this.Onvi_triChanging(value);
					this.SendPropertyChanging();
					this._vi_tri = value;
					this.SendPropertyChanged("vi_tri");
					this.Onvi_triChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_condition", DbType="Bit")]
		public System.Nullable<bool> has_condition
		{
			get
			{
				return this._has_condition;
			}
			set
			{
				if ((this._has_condition != value))
				{
					this.Onhas_conditionChanging(value);
					this.SendPropertyChanging();
					this._has_condition = value;
					this.SendPropertyChanged("has_condition");
					this.Onhas_conditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reason", DbType="NVarChar(100)")]
		public string reason
		{
			get
			{
				return this._reason;
			}
			set
			{
				if ((this._reason != value))
				{
					this.OnreasonChanging(value);
					this.SendPropertyChanging();
					this._reason = value;
					this.SendPropertyChanged("reason");
					this.OnreasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_gennetic", DbType="Bit")]
		public System.Nullable<bool> has_gennetic
		{
			get
			{
				return this._has_gennetic;
			}
			set
			{
				if ((this._has_gennetic != value))
				{
					this.Onhas_genneticChanging(value);
					this.SendPropertyChanging();
					this._has_gennetic = value;
					this.SendPropertyChanged("has_gennetic");
					this.Onhas_genneticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(500)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_need_sync", DbType="Bit")]
		public System.Nullable<bool> flag_need_sync
		{
			get
			{
				return this._flag_need_sync;
			}
			set
			{
				if ((this._flag_need_sync != value))
				{
					this.Onflag_need_syncChanging(value);
					this.SendPropertyChanging();
					this._flag_need_sync = value;
					this.SendPropertyChanged("flag_need_sync");
					this.Onflag_need_syncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_used", DbType="Bit")]
		public System.Nullable<bool> flag_used
		{
			get
			{
				return this._flag_used;
			}
			set
			{
				if ((this._flag_used != value))
				{
					this.Onflag_usedChanging(value);
					this.SendPropertyChanging();
					this._flag_used = value;
					this.SendPropertyChanged("flag_used");
					this.Onflag_usedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pattern_code", DbType="VarChar(50)")]
		public string pattern_code
		{
			get
			{
				return this._pattern_code;
			}
			set
			{
				if ((this._pattern_code != value))
				{
					this.Onpattern_codeChanging(value);
					this.SendPropertyChanging();
					this._pattern_code = value;
					this.SendPropertyChanged("pattern_code");
					this.Onpattern_codeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_ttd_result")]
	public partial class dtb_ttd_result : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _patient_code;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _mau_sac;
		
		private string _the_tich;
		
		private string _ly_giai;
		
		private string _PH;
		
		private System.Nullable<int> _mat_do;
		
		private System.Nullable<int> _tong_so_tinh_trung;
		
		private System.Nullable<int> _ty_le_tinh_trung_song;
		
		private System.Nullable<int> _di_dong_tien_toi;
		
		private System.Nullable<int> _di_dong_khong_tien_toi;
		
		private System.Nullable<int> _bat_dong;
		
		private System.Nullable<int> _hinh_thai_binh_thuong;
		
		private System.Nullable<int> _hinh_thai_bat_thuong_dau;
		
		private System.Nullable<int> _hinh_thai_bat_thuong_co;
		
		private System.Nullable<int> _hinh_thai_bat_thuong_duoi;
		
		private string _te_bao_hinh_tron;
		
		private string _ghi_chu;
		
		private System.Nullable<bool> _flag_need_sync;
		
		private System.Nullable<byte> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onmau_sacChanging(string value);
    partial void Onmau_sacChanged();
    partial void Onthe_tichChanging(string value);
    partial void Onthe_tichChanged();
    partial void Only_giaiChanging(string value);
    partial void Only_giaiChanged();
    partial void OnPHChanging(string value);
    partial void OnPHChanged();
    partial void Onmat_doChanging(System.Nullable<int> value);
    partial void Onmat_doChanged();
    partial void Ontong_so_tinh_trungChanging(System.Nullable<int> value);
    partial void Ontong_so_tinh_trungChanged();
    partial void Onty_le_tinh_trung_songChanging(System.Nullable<int> value);
    partial void Onty_le_tinh_trung_songChanged();
    partial void Ondi_dong_tien_toiChanging(System.Nullable<int> value);
    partial void Ondi_dong_tien_toiChanged();
    partial void Ondi_dong_khong_tien_toiChanging(System.Nullable<int> value);
    partial void Ondi_dong_khong_tien_toiChanged();
    partial void Onbat_dongChanging(System.Nullable<int> value);
    partial void Onbat_dongChanged();
    partial void Onhinh_thai_binh_thuongChanging(System.Nullable<int> value);
    partial void Onhinh_thai_binh_thuongChanged();
    partial void Onhinh_thai_bat_thuong_dauChanging(System.Nullable<int> value);
    partial void Onhinh_thai_bat_thuong_dauChanged();
    partial void Onhinh_thai_bat_thuong_coChanging(System.Nullable<int> value);
    partial void Onhinh_thai_bat_thuong_coChanged();
    partial void Onhinh_thai_bat_thuong_duoiChanging(System.Nullable<int> value);
    partial void Onhinh_thai_bat_thuong_duoiChanged();
    partial void Onte_bao_hinh_tronChanging(string value);
    partial void Onte_bao_hinh_tronChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onflag_need_syncChanging(System.Nullable<bool> value);
    partial void Onflag_need_syncChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    #endregion
		
		public dtb_ttd_result()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(100)")]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mau_sac", DbType="NVarChar(50)")]
		public string mau_sac
		{
			get
			{
				return this._mau_sac;
			}
			set
			{
				if ((this._mau_sac != value))
				{
					this.Onmau_sacChanging(value);
					this.SendPropertyChanging();
					this._mau_sac = value;
					this.SendPropertyChanged("mau_sac");
					this.Onmau_sacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_the_tich", DbType="NVarChar(50)")]
		public string the_tich
		{
			get
			{
				return this._the_tich;
			}
			set
			{
				if ((this._the_tich != value))
				{
					this.Onthe_tichChanging(value);
					this.SendPropertyChanging();
					this._the_tich = value;
					this.SendPropertyChanged("the_tich");
					this.Onthe_tichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ly_giai", DbType="NVarChar(50)")]
		public string ly_giai
		{
			get
			{
				return this._ly_giai;
			}
			set
			{
				if ((this._ly_giai != value))
				{
					this.Only_giaiChanging(value);
					this.SendPropertyChanging();
					this._ly_giai = value;
					this.SendPropertyChanged("ly_giai");
					this.Only_giaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PH", DbType="NVarChar(50)")]
		public string PH
		{
			get
			{
				return this._PH;
			}
			set
			{
				if ((this._PH != value))
				{
					this.OnPHChanging(value);
					this.SendPropertyChanging();
					this._PH = value;
					this.SendPropertyChanged("PH");
					this.OnPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_do", DbType="Int")]
		public System.Nullable<int> mat_do
		{
			get
			{
				return this._mat_do;
			}
			set
			{
				if ((this._mat_do != value))
				{
					this.Onmat_doChanging(value);
					this.SendPropertyChanging();
					this._mat_do = value;
					this.SendPropertyChanged("mat_do");
					this.Onmat_doChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_so_tinh_trung", DbType="Int")]
		public System.Nullable<int> tong_so_tinh_trung
		{
			get
			{
				return this._tong_so_tinh_trung;
			}
			set
			{
				if ((this._tong_so_tinh_trung != value))
				{
					this.Ontong_so_tinh_trungChanging(value);
					this.SendPropertyChanging();
					this._tong_so_tinh_trung = value;
					this.SendPropertyChanged("tong_so_tinh_trung");
					this.Ontong_so_tinh_trungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ty_le_tinh_trung_song", DbType="Int")]
		public System.Nullable<int> ty_le_tinh_trung_song
		{
			get
			{
				return this._ty_le_tinh_trung_song;
			}
			set
			{
				if ((this._ty_le_tinh_trung_song != value))
				{
					this.Onty_le_tinh_trung_songChanging(value);
					this.SendPropertyChanging();
					this._ty_le_tinh_trung_song = value;
					this.SendPropertyChanged("ty_le_tinh_trung_song");
					this.Onty_le_tinh_trung_songChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_di_dong_tien_toi", DbType="Int")]
		public System.Nullable<int> di_dong_tien_toi
		{
			get
			{
				return this._di_dong_tien_toi;
			}
			set
			{
				if ((this._di_dong_tien_toi != value))
				{
					this.Ondi_dong_tien_toiChanging(value);
					this.SendPropertyChanging();
					this._di_dong_tien_toi = value;
					this.SendPropertyChanged("di_dong_tien_toi");
					this.Ondi_dong_tien_toiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_di_dong_khong_tien_toi", DbType="Int")]
		public System.Nullable<int> di_dong_khong_tien_toi
		{
			get
			{
				return this._di_dong_khong_tien_toi;
			}
			set
			{
				if ((this._di_dong_khong_tien_toi != value))
				{
					this.Ondi_dong_khong_tien_toiChanging(value);
					this.SendPropertyChanging();
					this._di_dong_khong_tien_toi = value;
					this.SendPropertyChanged("di_dong_khong_tien_toi");
					this.Ondi_dong_khong_tien_toiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bat_dong", DbType="Int")]
		public System.Nullable<int> bat_dong
		{
			get
			{
				return this._bat_dong;
			}
			set
			{
				if ((this._bat_dong != value))
				{
					this.Onbat_dongChanging(value);
					this.SendPropertyChanging();
					this._bat_dong = value;
					this.SendPropertyChanged("bat_dong");
					this.Onbat_dongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_thai_binh_thuong", DbType="Int")]
		public System.Nullable<int> hinh_thai_binh_thuong
		{
			get
			{
				return this._hinh_thai_binh_thuong;
			}
			set
			{
				if ((this._hinh_thai_binh_thuong != value))
				{
					this.Onhinh_thai_binh_thuongChanging(value);
					this.SendPropertyChanging();
					this._hinh_thai_binh_thuong = value;
					this.SendPropertyChanged("hinh_thai_binh_thuong");
					this.Onhinh_thai_binh_thuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_thai_bat_thuong_dau", DbType="Int")]
		public System.Nullable<int> hinh_thai_bat_thuong_dau
		{
			get
			{
				return this._hinh_thai_bat_thuong_dau;
			}
			set
			{
				if ((this._hinh_thai_bat_thuong_dau != value))
				{
					this.Onhinh_thai_bat_thuong_dauChanging(value);
					this.SendPropertyChanging();
					this._hinh_thai_bat_thuong_dau = value;
					this.SendPropertyChanged("hinh_thai_bat_thuong_dau");
					this.Onhinh_thai_bat_thuong_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_thai_bat_thuong_co", DbType="Int")]
		public System.Nullable<int> hinh_thai_bat_thuong_co
		{
			get
			{
				return this._hinh_thai_bat_thuong_co;
			}
			set
			{
				if ((this._hinh_thai_bat_thuong_co != value))
				{
					this.Onhinh_thai_bat_thuong_coChanging(value);
					this.SendPropertyChanging();
					this._hinh_thai_bat_thuong_co = value;
					this.SendPropertyChanged("hinh_thai_bat_thuong_co");
					this.Onhinh_thai_bat_thuong_coChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_thai_bat_thuong_duoi", DbType="Int")]
		public System.Nullable<int> hinh_thai_bat_thuong_duoi
		{
			get
			{
				return this._hinh_thai_bat_thuong_duoi;
			}
			set
			{
				if ((this._hinh_thai_bat_thuong_duoi != value))
				{
					this.Onhinh_thai_bat_thuong_duoiChanging(value);
					this.SendPropertyChanging();
					this._hinh_thai_bat_thuong_duoi = value;
					this.SendPropertyChanged("hinh_thai_bat_thuong_duoi");
					this.Onhinh_thai_bat_thuong_duoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_te_bao_hinh_tron", DbType="NVarChar(50)")]
		public string te_bao_hinh_tron
		{
			get
			{
				return this._te_bao_hinh_tron;
			}
			set
			{
				if ((this._te_bao_hinh_tron != value))
				{
					this.Onte_bao_hinh_tronChanging(value);
					this.SendPropertyChanging();
					this._te_bao_hinh_tron = value;
					this.SendPropertyChanged("te_bao_hinh_tron");
					this.Onte_bao_hinh_tronChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(500)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_need_sync", DbType="Bit")]
		public System.Nullable<bool> flag_need_sync
		{
			get
			{
				return this._flag_need_sync;
			}
			set
			{
				if ((this._flag_need_sync != value))
				{
					this.Onflag_need_syncChanging(value);
					this.SendPropertyChanging();
					this._flag_need_sync = value;
					this.SendPropertyChanged("flag_need_sync");
					this.Onflag_need_syncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_male_relation")]
	public partial class dtb_male_relation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _patient_code;
		
		private string _fullname;
		
		private System.Nullable<System.DateTime> _date_of_birth;
		
		private string _identify;
		
		private System.Nullable<System.DateTime> _date_of_id;
		
		private string _address_of_id;
		
		private string _address;
		
		private string _email;
		
		private string _phone;
		
		private string _province_code;
		
		private System.Nullable<int> _nation_id;
		
		private string _district_code;
		
		private string _type_of_class;
		
		private string _ghi_chu;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private System.Nullable<bool> _flag_need_sync;
		
		private System.Nullable<byte> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    partial void OnidentifyChanging(string value);
    partial void OnidentifyChanged();
    partial void Ondate_of_idChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_idChanged();
    partial void Onaddress_of_idChanging(string value);
    partial void Onaddress_of_idChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onprovince_codeChanging(string value);
    partial void Onprovince_codeChanged();
    partial void Onnation_idChanging(System.Nullable<int> value);
    partial void Onnation_idChanged();
    partial void Ondistrict_codeChanging(string value);
    partial void Ondistrict_codeChanged();
    partial void Ontype_of_classChanging(string value);
    partial void Ontype_of_classChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onflag_need_syncChanging(System.Nullable<bool> value);
    partial void Onflag_need_syncChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    #endregion
		
		public dtb_male_relation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(100)")]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(100)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_birth
		{
			get
			{
				return this._date_of_birth;
			}
			set
			{
				if ((this._date_of_birth != value))
				{
					this.Ondate_of_birthChanging(value);
					this.SendPropertyChanging();
					this._date_of_birth = value;
					this.SendPropertyChanged("date_of_birth");
					this.Ondate_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identify", DbType="VarChar(100)")]
		public string identify
		{
			get
			{
				return this._identify;
			}
			set
			{
				if ((this._identify != value))
				{
					this.OnidentifyChanging(value);
					this.SendPropertyChanging();
					this._identify = value;
					this.SendPropertyChanged("identify");
					this.OnidentifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_id", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_id
		{
			get
			{
				return this._date_of_id;
			}
			set
			{
				if ((this._date_of_id != value))
				{
					this.Ondate_of_idChanging(value);
					this.SendPropertyChanging();
					this._date_of_id = value;
					this.SendPropertyChanged("date_of_id");
					this.Ondate_of_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_of_id", DbType="NVarChar(100)")]
		public string address_of_id
		{
			get
			{
				return this._address_of_id;
			}
			set
			{
				if ((this._address_of_id != value))
				{
					this.Onaddress_of_idChanging(value);
					this.SendPropertyChanging();
					this._address_of_id = value;
					this.SendPropertyChanged("address_of_id");
					this.Onaddress_of_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province_code", DbType="NVarChar(100)")]
		public string province_code
		{
			get
			{
				return this._province_code;
			}
			set
			{
				if ((this._province_code != value))
				{
					this.Onprovince_codeChanging(value);
					this.SendPropertyChanging();
					this._province_code = value;
					this.SendPropertyChanged("province_code");
					this.Onprovince_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nation_id", DbType="Int")]
		public System.Nullable<int> nation_id
		{
			get
			{
				return this._nation_id;
			}
			set
			{
				if ((this._nation_id != value))
				{
					this.Onnation_idChanging(value);
					this.SendPropertyChanging();
					this._nation_id = value;
					this.SendPropertyChanged("nation_id");
					this.Onnation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district_code", DbType="NVarChar(100)")]
		public string district_code
		{
			get
			{
				return this._district_code;
			}
			set
			{
				if ((this._district_code != value))
				{
					this.Ondistrict_codeChanging(value);
					this.SendPropertyChanging();
					this._district_code = value;
					this.SendPropertyChanged("district_code");
					this.Ondistrict_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_of_class", DbType="NVarChar(100)")]
		public string type_of_class
		{
			get
			{
				return this._type_of_class;
			}
			set
			{
				if ((this._type_of_class != value))
				{
					this.Ontype_of_classChanging(value);
					this.SendPropertyChanging();
					this._type_of_class = value;
					this.SendPropertyChanged("type_of_class");
					this.Ontype_of_classChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(500)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_need_sync", DbType="Bit")]
		public System.Nullable<bool> flag_need_sync
		{
			get
			{
				return this._flag_need_sync;
			}
			set
			{
				if ((this._flag_need_sync != value))
				{
					this.Onflag_need_syncChanging(value);
					this.SendPropertyChanging();
					this._flag_need_sync = value;
					this.SendPropertyChanged("flag_need_sync");
					this.Onflag_need_syncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_sperm_spec")]
	public partial class dtb_sperm_spec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _patient_code;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _height;
		
		private string _weight;
		
		private string _eye_color;
		
		private string _hair_color;
		
		private string _hair_style;
		
		private string _color;
		
		private string _ghi_chu;
		
		private System.Nullable<bool> _flag_need_sync;
		
		private System.Nullable<byte> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void OnheightChanging(string value);
    partial void OnheightChanged();
    partial void OnweightChanging(string value);
    partial void OnweightChanged();
    partial void Oneye_colorChanging(string value);
    partial void Oneye_colorChanged();
    partial void Onhair_colorChanging(string value);
    partial void Onhair_colorChanged();
    partial void Onhair_styleChanging(string value);
    partial void Onhair_styleChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onflag_need_syncChanging(System.Nullable<bool> value);
    partial void Onflag_need_syncChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    #endregion
		
		public dtb_sperm_spec()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(100)")]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="NVarChar(100)")]
		public string height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="NVarChar(100)")]
		public string weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eye_color", DbType="NVarChar(100)")]
		public string eye_color
		{
			get
			{
				return this._eye_color;
			}
			set
			{
				if ((this._eye_color != value))
				{
					this.Oneye_colorChanging(value);
					this.SendPropertyChanging();
					this._eye_color = value;
					this.SendPropertyChanged("eye_color");
					this.Oneye_colorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hair_color", DbType="NVarChar(100)")]
		public string hair_color
		{
			get
			{
				return this._hair_color;
			}
			set
			{
				if ((this._hair_color != value))
				{
					this.Onhair_colorChanging(value);
					this.SendPropertyChanging();
					this._hair_color = value;
					this.SendPropertyChanged("hair_color");
					this.Onhair_colorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hair_style", DbType="NVarChar(100)")]
		public string hair_style
		{
			get
			{
				return this._hair_style;
			}
			set
			{
				if ((this._hair_style != value))
				{
					this.Onhair_styleChanging(value);
					this.SendPropertyChanging();
					this._hair_style = value;
					this.SendPropertyChanged("hair_style");
					this.Onhair_styleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NVarChar(100)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(500)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_need_sync", DbType="Bit")]
		public System.Nullable<bool> flag_need_sync
		{
			get
			{
				return this._flag_need_sync;
			}
			set
			{
				if ((this._flag_need_sync != value))
				{
					this.Onflag_need_syncChanging(value);
					this.SendPropertyChanging();
					this._flag_need_sync = value;
					this.SendPropertyChanged("flag_need_sync");
					this.Onflag_need_syncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
