#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVPS.ServiceCheckFPForm.DBContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="htss")]
	public partial class InformationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdtb_sperm_send(dtb_sperm_send instance);
    partial void Updatedtb_sperm_send(dtb_sperm_send instance);
    partial void Deletedtb_sperm_send(dtb_sperm_send instance);
    partial void Insertdtb_patien_ovule_send(dtb_patien_ovule_send instance);
    partial void Updatedtb_patien_ovule_send(dtb_patien_ovule_send instance);
    partial void Deletedtb_patien_ovule_send(dtb_patien_ovule_send instance);
    partial void Insertdtb_class(dtb_class instance);
    partial void Updatedtb_class(dtb_class instance);
    partial void Deletedtb_class(dtb_class instance);
    partial void Insertdtb_district(dtb_district instance);
    partial void Updatedtb_district(dtb_district instance);
    partial void Deletedtb_district(dtb_district instance);
    partial void Insertdtb_level(dtb_level instance);
    partial void Updatedtb_level(dtb_level instance);
    partial void Deletedtb_level(dtb_level instance);
    partial void Insertdtb_province(dtb_province instance);
    partial void Updatedtb_province(dtb_province instance);
    partial void Deletedtb_province(dtb_province instance);
    #endregion
		
		public InformationDataContext() : 
				base(global::BVPS.ServiceCheckFPForm.Properties.Settings.Default.htssConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InformationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InformationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InformationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InformationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dtb_sperm_send> dtb_sperm_sends
		{
			get
			{
				return this.GetTable<dtb_sperm_send>();
			}
		}
		
		public System.Data.Linq.Table<dtb_patien_ovule_send> dtb_patien_ovule_sends
		{
			get
			{
				return this.GetTable<dtb_patien_ovule_send>();
			}
		}
		
		public System.Data.Linq.Table<dtb_class> dtb_classes
		{
			get
			{
				return this.GetTable<dtb_class>();
			}
		}
		
		public System.Data.Linq.Table<dtb_district> dtb_districts
		{
			get
			{
				return this.GetTable<dtb_district>();
			}
		}
		
		public System.Data.Linq.Table<dtb_level> dtb_levels
		{
			get
			{
				return this.GetTable<dtb_level>();
			}
		}
		
		public System.Data.Linq.Table<dtb_province> dtb_provinces
		{
			get
			{
				return this.GetTable<dtb_province>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_sperm_send")]
	public partial class dtb_sperm_send : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _patient_code;
		
		private string _fullname;
		
		private System.Nullable<System.DateTime> _dateofbirth;
		
		private string _identifier;
		
		private System.Nullable<System.DateTime> _dateofid;
		
		private string _AddressOfId;
		
		private string _Adddress;
		
		private string _phone;
		
		private string _email;
		
		private System.Nullable<int> _level_id;
		
		private string _job;
		
		private System.Nullable<int> _nation_id;
		
		private System.Nullable<int> _class_id;
		
		private string _province_code;
		
		private string _district_code;
		
		private System.Nullable<bool> _maried;
		
		private System.Nullable<bool> _haschild;
		
		private System.Nullable<int> _numofchild;
		
		private System.Nullable<int> _yearofchildlast;
		
		private System.Nullable<int> _dayofhavebaby;
		
		private string _heathstatus;
		
		private string _historyofpatient;
		
		private string _FPNgonCaiPhai;
		
		private string _FPNgonCaiTrai;
		
		private string _FPNgonTroPhai;
		
		private string _FPNgonTroTrai;
		
		private string _historyoffamily;
		
		private string _FPBase64NgonCaiPhai;
		
		private string _FPBase64NgonCaiTrai;
		
		private string _FPBase64NgonTroPhai;
		
		private string _FPBase64NgonTroTrai;
		
		private System.Nullable<System.DateTime> _Create_Date;
		
		private System.Nullable<bool> _FlagNeedSync;
		
		private string _MaTrungTam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpatient_codeChanging(string value);
    partial void Onpatient_codeChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OndateofbirthChanging(System.Nullable<System.DateTime> value);
    partial void OndateofbirthChanged();
    partial void OnidentifierChanging(string value);
    partial void OnidentifierChanged();
    partial void OndateofidChanging(System.Nullable<System.DateTime> value);
    partial void OndateofidChanged();
    partial void OnAddressOfIdChanging(string value);
    partial void OnAddressOfIdChanged();
    partial void OnAdddressChanging(string value);
    partial void OnAdddressChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onlevel_idChanging(System.Nullable<int> value);
    partial void Onlevel_idChanged();
    partial void OnjobChanging(string value);
    partial void OnjobChanged();
    partial void Onnation_idChanging(System.Nullable<int> value);
    partial void Onnation_idChanged();
    partial void Onclass_idChanging(System.Nullable<int> value);
    partial void Onclass_idChanged();
    partial void Onprovince_codeChanging(string value);
    partial void Onprovince_codeChanged();
    partial void Ondistrict_codeChanging(string value);
    partial void Ondistrict_codeChanged();
    partial void OnmariedChanging(System.Nullable<bool> value);
    partial void OnmariedChanged();
    partial void OnhaschildChanging(System.Nullable<bool> value);
    partial void OnhaschildChanged();
    partial void OnnumofchildChanging(System.Nullable<int> value);
    partial void OnnumofchildChanged();
    partial void OnyearofchildlastChanging(System.Nullable<int> value);
    partial void OnyearofchildlastChanged();
    partial void OndayofhavebabyChanging(System.Nullable<int> value);
    partial void OndayofhavebabyChanged();
    partial void OnheathstatusChanging(string value);
    partial void OnheathstatusChanged();
    partial void OnhistoryofpatientChanging(string value);
    partial void OnhistoryofpatientChanged();
    partial void OnFPNgonCaiPhaiChanging(string value);
    partial void OnFPNgonCaiPhaiChanged();
    partial void OnFPNgonCaiTraiChanging(string value);
    partial void OnFPNgonCaiTraiChanged();
    partial void OnFPNgonTroPhaiChanging(string value);
    partial void OnFPNgonTroPhaiChanged();
    partial void OnFPNgonTroTraiChanging(string value);
    partial void OnFPNgonTroTraiChanged();
    partial void OnhistoryoffamilyChanging(string value);
    partial void OnhistoryoffamilyChanged();
    partial void OnFPBase64NgonCaiPhaiChanging(string value);
    partial void OnFPBase64NgonCaiPhaiChanged();
    partial void OnFPBase64NgonCaiTraiChanging(string value);
    partial void OnFPBase64NgonCaiTraiChanged();
    partial void OnFPBase64NgonTroPhaiChanging(string value);
    partial void OnFPBase64NgonTroPhaiChanged();
    partial void OnFPBase64NgonTroTraiChanging(string value);
    partial void OnFPBase64NgonTroTraiChanged();
    partial void OnCreate_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_DateChanged();
    partial void OnFlagNeedSyncChanging(System.Nullable<bool> value);
    partial void OnFlagNeedSyncChanged();
    partial void OnMaTrungTamChanging(string value);
    partial void OnMaTrungTamChanged();
    #endregion
		
		public dtb_sperm_send()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_code", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string patient_code
		{
			get
			{
				return this._patient_code;
			}
			set
			{
				if ((this._patient_code != value))
				{
					this.Onpatient_codeChanging(value);
					this.SendPropertyChanging();
					this._patient_code = value;
					this.SendPropertyChanged("patient_code");
					this.Onpatient_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(100)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofbirth", DbType="Date")]
		public System.Nullable<System.DateTime> dateofbirth
		{
			get
			{
				return this._dateofbirth;
			}
			set
			{
				if ((this._dateofbirth != value))
				{
					this.OndateofbirthChanging(value);
					this.SendPropertyChanging();
					this._dateofbirth = value;
					this.SendPropertyChanged("dateofbirth");
					this.OndateofbirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="VarChar(100)")]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this.OnidentifierChanging(value);
					this.SendPropertyChanging();
					this._identifier = value;
					this.SendPropertyChanged("identifier");
					this.OnidentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofid", DbType="Date")]
		public System.Nullable<System.DateTime> dateofid
		{
			get
			{
				return this._dateofid;
			}
			set
			{
				if ((this._dateofid != value))
				{
					this.OndateofidChanging(value);
					this.SendPropertyChanging();
					this._dateofid = value;
					this.SendPropertyChanged("dateofid");
					this.OndateofidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressOfId", DbType="NVarChar(100)")]
		public string AddressOfId
		{
			get
			{
				return this._AddressOfId;
			}
			set
			{
				if ((this._AddressOfId != value))
				{
					this.OnAddressOfIdChanging(value);
					this.SendPropertyChanging();
					this._AddressOfId = value;
					this.SendPropertyChanged("AddressOfId");
					this.OnAddressOfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adddress", DbType="NVarChar(100)")]
		public string Adddress
		{
			get
			{
				return this._Adddress;
			}
			set
			{
				if ((this._Adddress != value))
				{
					this.OnAdddressChanging(value);
					this.SendPropertyChanging();
					this._Adddress = value;
					this.SendPropertyChanged("Adddress");
					this.OnAdddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_id", DbType="Int")]
		public System.Nullable<int> level_id
		{
			get
			{
				return this._level_id;
			}
			set
			{
				if ((this._level_id != value))
				{
					this.Onlevel_idChanging(value);
					this.SendPropertyChanging();
					this._level_id = value;
					this.SendPropertyChanged("level_id");
					this.Onlevel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job", DbType="NVarChar(100)")]
		public string job
		{
			get
			{
				return this._job;
			}
			set
			{
				if ((this._job != value))
				{
					this.OnjobChanging(value);
					this.SendPropertyChanging();
					this._job = value;
					this.SendPropertyChanged("job");
					this.OnjobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nation_id", DbType="Int")]
		public System.Nullable<int> nation_id
		{
			get
			{
				return this._nation_id;
			}
			set
			{
				if ((this._nation_id != value))
				{
					this.Onnation_idChanging(value);
					this.SendPropertyChanging();
					this._nation_id = value;
					this.SendPropertyChanged("nation_id");
					this.Onnation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_id", DbType="Int")]
		public System.Nullable<int> class_id
		{
			get
			{
				return this._class_id;
			}
			set
			{
				if ((this._class_id != value))
				{
					this.Onclass_idChanging(value);
					this.SendPropertyChanging();
					this._class_id = value;
					this.SendPropertyChanged("class_id");
					this.Onclass_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province_code", DbType="VarChar(100)")]
		public string province_code
		{
			get
			{
				return this._province_code;
			}
			set
			{
				if ((this._province_code != value))
				{
					this.Onprovince_codeChanging(value);
					this.SendPropertyChanging();
					this._province_code = value;
					this.SendPropertyChanged("province_code");
					this.Onprovince_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district_code", DbType="VarChar(100)")]
		public string district_code
		{
			get
			{
				return this._district_code;
			}
			set
			{
				if ((this._district_code != value))
				{
					this.Ondistrict_codeChanging(value);
					this.SendPropertyChanging();
					this._district_code = value;
					this.SendPropertyChanged("district_code");
					this.Ondistrict_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maried", DbType="Bit")]
		public System.Nullable<bool> maried
		{
			get
			{
				return this._maried;
			}
			set
			{
				if ((this._maried != value))
				{
					this.OnmariedChanging(value);
					this.SendPropertyChanging();
					this._maried = value;
					this.SendPropertyChanged("maried");
					this.OnmariedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haschild", DbType="Bit")]
		public System.Nullable<bool> haschild
		{
			get
			{
				return this._haschild;
			}
			set
			{
				if ((this._haschild != value))
				{
					this.OnhaschildChanging(value);
					this.SendPropertyChanging();
					this._haschild = value;
					this.SendPropertyChanged("haschild");
					this.OnhaschildChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numofchild", DbType="Int")]
		public System.Nullable<int> numofchild
		{
			get
			{
				return this._numofchild;
			}
			set
			{
				if ((this._numofchild != value))
				{
					this.OnnumofchildChanging(value);
					this.SendPropertyChanging();
					this._numofchild = value;
					this.SendPropertyChanged("numofchild");
					this.OnnumofchildChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearofchildlast", DbType="Int")]
		public System.Nullable<int> yearofchildlast
		{
			get
			{
				return this._yearofchildlast;
			}
			set
			{
				if ((this._yearofchildlast != value))
				{
					this.OnyearofchildlastChanging(value);
					this.SendPropertyChanging();
					this._yearofchildlast = value;
					this.SendPropertyChanged("yearofchildlast");
					this.OnyearofchildlastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dayofhavebaby", DbType="Int")]
		public System.Nullable<int> dayofhavebaby
		{
			get
			{
				return this._dayofhavebaby;
			}
			set
			{
				if ((this._dayofhavebaby != value))
				{
					this.OndayofhavebabyChanging(value);
					this.SendPropertyChanging();
					this._dayofhavebaby = value;
					this.SendPropertyChanged("dayofhavebaby");
					this.OndayofhavebabyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heathstatus", DbType="NVarChar(100)")]
		public string heathstatus
		{
			get
			{
				return this._heathstatus;
			}
			set
			{
				if ((this._heathstatus != value))
				{
					this.OnheathstatusChanging(value);
					this.SendPropertyChanging();
					this._heathstatus = value;
					this.SendPropertyChanged("heathstatus");
					this.OnheathstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_historyofpatient", DbType="NVarChar(100)")]
		public string historyofpatient
		{
			get
			{
				return this._historyofpatient;
			}
			set
			{
				if ((this._historyofpatient != value))
				{
					this.OnhistoryofpatientChanging(value);
					this.SendPropertyChanging();
					this._historyofpatient = value;
					this.SendPropertyChanged("historyofpatient");
					this.OnhistoryofpatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNgonCaiPhai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FPNgonCaiPhai
		{
			get
			{
				return this._FPNgonCaiPhai;
			}
			set
			{
				if ((this._FPNgonCaiPhai != value))
				{
					this.OnFPNgonCaiPhaiChanging(value);
					this.SendPropertyChanging();
					this._FPNgonCaiPhai = value;
					this.SendPropertyChanged("FPNgonCaiPhai");
					this.OnFPNgonCaiPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNgonCaiTrai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FPNgonCaiTrai
		{
			get
			{
				return this._FPNgonCaiTrai;
			}
			set
			{
				if ((this._FPNgonCaiTrai != value))
				{
					this.OnFPNgonCaiTraiChanging(value);
					this.SendPropertyChanging();
					this._FPNgonCaiTrai = value;
					this.SendPropertyChanged("FPNgonCaiTrai");
					this.OnFPNgonCaiTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNgonTroPhai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FPNgonTroPhai
		{
			get
			{
				return this._FPNgonTroPhai;
			}
			set
			{
				if ((this._FPNgonTroPhai != value))
				{
					this.OnFPNgonTroPhaiChanging(value);
					this.SendPropertyChanging();
					this._FPNgonTroPhai = value;
					this.SendPropertyChanged("FPNgonTroPhai");
					this.OnFPNgonTroPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNgonTroTrai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FPNgonTroTrai
		{
			get
			{
				return this._FPNgonTroTrai;
			}
			set
			{
				if ((this._FPNgonTroTrai != value))
				{
					this.OnFPNgonTroTraiChanging(value);
					this.SendPropertyChanging();
					this._FPNgonTroTrai = value;
					this.SendPropertyChanged("FPNgonTroTrai");
					this.OnFPNgonTroTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_historyoffamily", DbType="NVarChar(100)")]
		public string historyoffamily
		{
			get
			{
				return this._historyoffamily;
			}
			set
			{
				if ((this._historyoffamily != value))
				{
					this.OnhistoryoffamilyChanging(value);
					this.SendPropertyChanging();
					this._historyoffamily = value;
					this.SendPropertyChanged("historyoffamily");
					this.OnhistoryoffamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPBase64NgonCaiPhai", DbType="NVarChar(MAX)")]
		public string FPBase64NgonCaiPhai
		{
			get
			{
				return this._FPBase64NgonCaiPhai;
			}
			set
			{
				if ((this._FPBase64NgonCaiPhai != value))
				{
					this.OnFPBase64NgonCaiPhaiChanging(value);
					this.SendPropertyChanging();
					this._FPBase64NgonCaiPhai = value;
					this.SendPropertyChanged("FPBase64NgonCaiPhai");
					this.OnFPBase64NgonCaiPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPBase64NgonCaiTrai", DbType="NVarChar(MAX)")]
		public string FPBase64NgonCaiTrai
		{
			get
			{
				return this._FPBase64NgonCaiTrai;
			}
			set
			{
				if ((this._FPBase64NgonCaiTrai != value))
				{
					this.OnFPBase64NgonCaiTraiChanging(value);
					this.SendPropertyChanging();
					this._FPBase64NgonCaiTrai = value;
					this.SendPropertyChanged("FPBase64NgonCaiTrai");
					this.OnFPBase64NgonCaiTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPBase64NgonTroPhai", DbType="NVarChar(MAX)")]
		public string FPBase64NgonTroPhai
		{
			get
			{
				return this._FPBase64NgonTroPhai;
			}
			set
			{
				if ((this._FPBase64NgonTroPhai != value))
				{
					this.OnFPBase64NgonTroPhaiChanging(value);
					this.SendPropertyChanging();
					this._FPBase64NgonTroPhai = value;
					this.SendPropertyChanged("FPBase64NgonTroPhai");
					this.OnFPBase64NgonTroPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPBase64NgonTroTrai", DbType="NVarChar(MAX)")]
		public string FPBase64NgonTroTrai
		{
			get
			{
				return this._FPBase64NgonTroTrai;
			}
			set
			{
				if ((this._FPBase64NgonTroTrai != value))
				{
					this.OnFPBase64NgonTroTraiChanging(value);
					this.SendPropertyChanging();
					this._FPBase64NgonTroTrai = value;
					this.SendPropertyChanged("FPBase64NgonTroTrai");
					this.OnFPBase64NgonTroTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Create_Date
		{
			get
			{
				return this._Create_Date;
			}
			set
			{
				if ((this._Create_Date != value))
				{
					this.OnCreate_DateChanging(value);
					this.SendPropertyChanging();
					this._Create_Date = value;
					this.SendPropertyChanged("Create_Date");
					this.OnCreate_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagNeedSync", DbType="Bit")]
		public System.Nullable<bool> FlagNeedSync
		{
			get
			{
				return this._FlagNeedSync;
			}
			set
			{
				if ((this._FlagNeedSync != value))
				{
					this.OnFlagNeedSyncChanging(value);
					this.SendPropertyChanging();
					this._FlagNeedSync = value;
					this.SendPropertyChanged("FlagNeedSync");
					this.OnFlagNeedSyncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrungTam", DbType="NVarChar(10)")]
		public string MaTrungTam
		{
			get
			{
				return this._MaTrungTam;
			}
			set
			{
				if ((this._MaTrungTam != value))
				{
					this.OnMaTrungTamChanging(value);
					this.SendPropertyChanging();
					this._MaTrungTam = value;
					this.SendPropertyChanged("MaTrungTam");
					this.OnMaTrungTamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_patien_ovule_send")]
	public partial class dtb_patien_ovule_send : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Patien_code;
		
		private string _Fullname;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private string _Identify;
		
		private System.Nullable<System.DateTime> _DateOfId;
		
		private string _AddressOfId;
		
		private string _Address;
		
		private string _Province_code;
		
		private string _District_code;
		
		private string _Phone;
		
		private string _Email;
		
		private string _FPNgonCaiPhai;
		
		private string _FPNgonCaiTrai;
		
		private string _FPNgonTroPhai;
		
		private string _FPNgonTroTrai;
		
		private System.Nullable<int> _Nation_id;
		
		private string _FPBase64NgonCaiPhai;
		
		private string _FPBase64NgonCaiTrai;
		
		private string _FPBase64NgonTroPhai;
		
		private string _FPBase64NgonTroTrai;
		
		private System.Nullable<System.DateTime> _Created_date;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _FlagNeedSync;
		
		private System.Nullable<int> _class_id;
		
		private string _MaTrungTam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPatien_codeChanging(string value);
    partial void OnPatien_codeChanged();
    partial void OnFullnameChanging(string value);
    partial void OnFullnameChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnIdentifyChanging(string value);
    partial void OnIdentifyChanged();
    partial void OnDateOfIdChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfIdChanged();
    partial void OnAddressOfIdChanging(string value);
    partial void OnAddressOfIdChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnProvince_codeChanging(string value);
    partial void OnProvince_codeChanged();
    partial void OnDistrict_codeChanging(string value);
    partial void OnDistrict_codeChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFPNgonCaiPhaiChanging(string value);
    partial void OnFPNgonCaiPhaiChanged();
    partial void OnFPNgonCaiTraiChanging(string value);
    partial void OnFPNgonCaiTraiChanged();
    partial void OnFPNgonTroPhaiChanging(string value);
    partial void OnFPNgonTroPhaiChanged();
    partial void OnFPNgonTroTraiChanging(string value);
    partial void OnFPNgonTroTraiChanged();
    partial void OnNation_idChanging(System.Nullable<int> value);
    partial void OnNation_idChanged();
    partial void OnFPBase64NgonCaiPhaiChanging(string value);
    partial void OnFPBase64NgonCaiPhaiChanged();
    partial void OnFPBase64NgonCaiTraiChanging(string value);
    partial void OnFPBase64NgonCaiTraiChanged();
    partial void OnFPBase64NgonTroPhaiChanging(string value);
    partial void OnFPBase64NgonTroPhaiChanged();
    partial void OnFPBase64NgonTroTraiChanging(string value);
    partial void OnFPBase64NgonTroTraiChanged();
    partial void OnCreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreated_dateChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnFlagNeedSyncChanging(System.Nullable<bool> value);
    partial void OnFlagNeedSyncChanged();
    partial void Onclass_idChanging(System.Nullable<int> value);
    partial void Onclass_idChanged();
    partial void OnMaTrungTamChanging(string value);
    partial void OnMaTrungTamChanged();
    #endregion
		
		public dtb_patien_ovule_send()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patien_code", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Patien_code
		{
			get
			{
				return this._Patien_code;
			}
			set
			{
				if ((this._Patien_code != value))
				{
					this.OnPatien_codeChanging(value);
					this.SendPropertyChanging();
					this._Patien_code = value;
					this.SendPropertyChanged("Patien_code");
					this.OnPatien_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(100)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this.OnFullnameChanging(value);
					this.SendPropertyChanging();
					this._Fullname = value;
					this.SendPropertyChanged("Fullname");
					this.OnFullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identify", DbType="VarChar(100)")]
		public string Identify
		{
			get
			{
				return this._Identify;
			}
			set
			{
				if ((this._Identify != value))
				{
					this.OnIdentifyChanging(value);
					this.SendPropertyChanging();
					this._Identify = value;
					this.SendPropertyChanged("Identify");
					this.OnIdentifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfId", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfId
		{
			get
			{
				return this._DateOfId;
			}
			set
			{
				if ((this._DateOfId != value))
				{
					this.OnDateOfIdChanging(value);
					this.SendPropertyChanging();
					this._DateOfId = value;
					this.SendPropertyChanged("DateOfId");
					this.OnDateOfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressOfId", DbType="NVarChar(100)")]
		public string AddressOfId
		{
			get
			{
				return this._AddressOfId;
			}
			set
			{
				if ((this._AddressOfId != value))
				{
					this.OnAddressOfIdChanging(value);
					this.SendPropertyChanging();
					this._AddressOfId = value;
					this.SendPropertyChanged("AddressOfId");
					this.OnAddressOfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province_code", DbType="NVarChar(100)")]
		public string Province_code
		{
			get
			{
				return this._Province_code;
			}
			set
			{
				if ((this._Province_code != value))
				{
					this.OnProvince_codeChanging(value);
					this.SendPropertyChanging();
					this._Province_code = value;
					this.SendPropertyChanged("Province_code");
					this.OnProvince_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District_code", DbType="NVarChar(100)")]
		public string District_code
		{
			get
			{
				return this._District_code;
			}
			set
			{
				if ((this._District_code != value))
				{
					this.OnDistrict_codeChanging(value);
					this.SendPropertyChanging();
					this._District_code = value;
					this.SendPropertyChanged("District_code");
					this.OnDistrict_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(100)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNgonCaiPhai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FPNgonCaiPhai
		{
			get
			{
				return this._FPNgonCaiPhai;
			}
			set
			{
				if ((this._FPNgonCaiPhai != value))
				{
					this.OnFPNgonCaiPhaiChanging(value);
					this.SendPropertyChanging();
					this._FPNgonCaiPhai = value;
					this.SendPropertyChanged("FPNgonCaiPhai");
					this.OnFPNgonCaiPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNgonCaiTrai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FPNgonCaiTrai
		{
			get
			{
				return this._FPNgonCaiTrai;
			}
			set
			{
				if ((this._FPNgonCaiTrai != value))
				{
					this.OnFPNgonCaiTraiChanging(value);
					this.SendPropertyChanging();
					this._FPNgonCaiTrai = value;
					this.SendPropertyChanged("FPNgonCaiTrai");
					this.OnFPNgonCaiTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNgonTroPhai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FPNgonTroPhai
		{
			get
			{
				return this._FPNgonTroPhai;
			}
			set
			{
				if ((this._FPNgonTroPhai != value))
				{
					this.OnFPNgonTroPhaiChanging(value);
					this.SendPropertyChanging();
					this._FPNgonTroPhai = value;
					this.SendPropertyChanged("FPNgonTroPhai");
					this.OnFPNgonTroPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNgonTroTrai", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FPNgonTroTrai
		{
			get
			{
				return this._FPNgonTroTrai;
			}
			set
			{
				if ((this._FPNgonTroTrai != value))
				{
					this.OnFPNgonTroTraiChanging(value);
					this.SendPropertyChanging();
					this._FPNgonTroTrai = value;
					this.SendPropertyChanged("FPNgonTroTrai");
					this.OnFPNgonTroTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nation_id", DbType="Int")]
		public System.Nullable<int> Nation_id
		{
			get
			{
				return this._Nation_id;
			}
			set
			{
				if ((this._Nation_id != value))
				{
					this.OnNation_idChanging(value);
					this.SendPropertyChanging();
					this._Nation_id = value;
					this.SendPropertyChanged("Nation_id");
					this.OnNation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPBase64NgonCaiPhai", DbType="NVarChar(MAX)")]
		public string FPBase64NgonCaiPhai
		{
			get
			{
				return this._FPBase64NgonCaiPhai;
			}
			set
			{
				if ((this._FPBase64NgonCaiPhai != value))
				{
					this.OnFPBase64NgonCaiPhaiChanging(value);
					this.SendPropertyChanging();
					this._FPBase64NgonCaiPhai = value;
					this.SendPropertyChanged("FPBase64NgonCaiPhai");
					this.OnFPBase64NgonCaiPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPBase64NgonCaiTrai", DbType="NVarChar(MAX)")]
		public string FPBase64NgonCaiTrai
		{
			get
			{
				return this._FPBase64NgonCaiTrai;
			}
			set
			{
				if ((this._FPBase64NgonCaiTrai != value))
				{
					this.OnFPBase64NgonCaiTraiChanging(value);
					this.SendPropertyChanging();
					this._FPBase64NgonCaiTrai = value;
					this.SendPropertyChanged("FPBase64NgonCaiTrai");
					this.OnFPBase64NgonCaiTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPBase64NgonTroPhai", DbType="NVarChar(MAX)")]
		public string FPBase64NgonTroPhai
		{
			get
			{
				return this._FPBase64NgonTroPhai;
			}
			set
			{
				if ((this._FPBase64NgonTroPhai != value))
				{
					this.OnFPBase64NgonTroPhaiChanging(value);
					this.SendPropertyChanging();
					this._FPBase64NgonTroPhai = value;
					this.SendPropertyChanged("FPBase64NgonTroPhai");
					this.OnFPBase64NgonTroPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPBase64NgonTroTrai", DbType="NVarChar(MAX)")]
		public string FPBase64NgonTroTrai
		{
			get
			{
				return this._FPBase64NgonTroTrai;
			}
			set
			{
				if ((this._FPBase64NgonTroTrai != value))
				{
					this.OnFPBase64NgonTroTraiChanging(value);
					this.SendPropertyChanging();
					this._FPBase64NgonTroTrai = value;
					this.SendPropertyChanged("FPBase64NgonTroTrai");
					this.OnFPBase64NgonTroTraiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_date", DbType="Date")]
		public System.Nullable<System.DateTime> Created_date
		{
			get
			{
				return this._Created_date;
			}
			set
			{
				if ((this._Created_date != value))
				{
					this.OnCreated_dateChanging(value);
					this.SendPropertyChanging();
					this._Created_date = value;
					this.SendPropertyChanged("Created_date");
					this.OnCreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagNeedSync", DbType="Bit")]
		public System.Nullable<bool> FlagNeedSync
		{
			get
			{
				return this._FlagNeedSync;
			}
			set
			{
				if ((this._FlagNeedSync != value))
				{
					this.OnFlagNeedSyncChanging(value);
					this.SendPropertyChanging();
					this._FlagNeedSync = value;
					this.SendPropertyChanged("FlagNeedSync");
					this.OnFlagNeedSyncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_id", DbType="Int")]
		public System.Nullable<int> class_id
		{
			get
			{
				return this._class_id;
			}
			set
			{
				if ((this._class_id != value))
				{
					this.Onclass_idChanging(value);
					this.SendPropertyChanging();
					this._class_id = value;
					this.SendPropertyChanged("class_id");
					this.Onclass_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrungTam", DbType="NVarChar(10)")]
		public string MaTrungTam
		{
			get
			{
				return this._MaTrungTam;
			}
			set
			{
				if ((this._MaTrungTam != value))
				{
					this.OnMaTrungTamChanging(value);
					this.SendPropertyChanging();
					this._MaTrungTam = value;
					this.SendPropertyChanged("MaTrungTam");
					this.OnMaTrungTamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_class")]
	public partial class dtb_class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public dtb_class()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(254)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_district")]
	public partial class dtb_district : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _district_code;
		
		private string _district_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondistrict_codeChanging(string value);
    partial void Ondistrict_codeChanged();
    partial void Ondistrict_nameChanging(string value);
    partial void Ondistrict_nameChanged();
    #endregion
		
		public dtb_district()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district_code", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string district_code
		{
			get
			{
				return this._district_code;
			}
			set
			{
				if ((this._district_code != value))
				{
					this.Ondistrict_codeChanging(value);
					this.SendPropertyChanging();
					this._district_code = value;
					this.SendPropertyChanged("district_code");
					this.Ondistrict_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string district_name
		{
			get
			{
				return this._district_name;
			}
			set
			{
				if ((this._district_name != value))
				{
					this.Ondistrict_nameChanging(value);
					this.SendPropertyChanging();
					this._district_name = value;
					this.SendPropertyChanged("district_name");
					this.Ondistrict_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_level")]
	public partial class dtb_level : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public dtb_level()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(254)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dtb_province")]
	public partial class dtb_province : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _province_code;
		
		private string _province_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onprovince_codeChanging(string value);
    partial void Onprovince_codeChanged();
    partial void Onprovince_nameChanging(string value);
    partial void Onprovince_nameChanged();
    #endregion
		
		public dtb_province()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province_code", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string province_code
		{
			get
			{
				return this._province_code;
			}
			set
			{
				if ((this._province_code != value))
				{
					this.Onprovince_codeChanging(value);
					this.SendPropertyChanging();
					this._province_code = value;
					this.SendPropertyChanged("province_code");
					this.Onprovince_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string province_name
		{
			get
			{
				return this._province_name;
			}
			set
			{
				if ((this._province_name != value))
				{
					this.Onprovince_nameChanging(value);
					this.SendPropertyChanging();
					this._province_name = value;
					this.SendPropertyChanged("province_name");
					this.Onprovince_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
